---
layer: L2
stage: "06"
stage_name: "review"
sub_stage_enum:
  - "06_in_progress"
  - "06_completed"
applicable_stop_points:
  - "over_eng"
  - "pii"
  - "adr_drift"
output_files:
  - "output/review-report.md"
  - "output/p0-p1-issues.md"  # conditional: only if P0/P1 issues exist
next_stage: "07"
---

# Stage 06 — review (L2)

Code review across 7 dimensions (correctness, security, performance, complexity, tests, docs, conventions) over what stage 04 delivered and stage 05 verified. P0/P1 issues trigger a fix loop (loopback to stage 04 — new wave or regeneration of existing wave). P2/P3 issues become tech debt recorded in `{{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md` and the cycle proceeds to merge (07).

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/06_review/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/05_verification/output/verification-report.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md | L4 | yes |
| 6 | {{PROJECT_ROOT}}/.icm-main/docs/decisions/ | L3 | conditional: read ADRs referenced in plan.md (sample-check, not full content) |
| 7 | {{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md | L3 | conditional: exists if tier ≠ experimental — append new P2/P3 here |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/xp-conventions.md | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/stop-points.md | L3 | yes |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/requesting-code-review-200tok.md | L3 | yes |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/receiving-code-review-200tok.md | L3 | yes |
| 12 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/06_review/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 13 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/ in full — review focused on files in `Files touched` declared for each task in plan.md.
- Outputs of stages 00, 01, 03, 04, 07, 08 — not relevant for review (verification-report already consolidates what matters from 04+05).
- ADRs in {{PROJECT_ROOT}}/.icm-main/docs/decisions/ NOT referenced in plan.md.
- {{PROJECT_ROOT}}/.icm-main/docs/lessons.md (lessons were already pre-injected in the stage 04 flow, not relevant to review).

## Process

1. **Pre-flight:** validate required Input paths; sub_stage `06_in_progress`. verification-report.md ABSENT → `BLOCKED_ERROR`.
2. **Spawn reviewer subagent:** independent subagent reads verification-report + plan.md + files in `Files touched`. Does not confuse itself with the author. Consults requesting/receiving 200tok summaries.
3. **Review across 7 dimensions** (one pass per dimension, recording findings):
   - **correctness** — behavior matches the task's 4-block contract?
   - **security** — input validation, secrets, authz, injection, PII leaking?
   - **performance** — hot path with undue complexity, N+1, leak?
   - **complexity** — over-engineering, unnecessary abstractions, dead code?
   - **tests** — cover critical paths? test the contract, not the implementation?
   - **docs** — docstrings, README, applied ADR, comments where non-obvious?
   - **conventions** — matches xp-conventions.md (naming, imports, formatting)?
4. **Classify issues** as P0/P1/P2/P3:
   - **P0** — bug affecting declared functionality in plan, active vulnerability, regression.
   - **P1** — high non-immediate risk (rare race condition, performance gap, untested edge case).
   - **P2** — relevant tech debt (desirable refactor, low coverage).
   - **P3** — cosmetic (naming, comment, import order).
5. **Detect stop points** during the review:
   - 3+ new abstraction layers without requirement → `over_eng` (calibrated by tier).
   - Logs/schema with PII in plaintext → `pii` (calibrated by tier).
   - Implementation diverges from active ADR without declared superseding → `adr_drift`.
6. **If P0/P1 exist (fix loop — loopback to stage 04, WITHOUT human gate):**
   - Write `output/p0-p1-issues.md` with each issue: file, line, description, recommendation.
   - Follow Case B (loopback) in the `## End of stage handoff` section of this L2 — auto-transition L1 to `stage_atual: "04"` + render kickoff in `04_implementation_waves/_kickoff.md` + atomic commit + KICKOFF block + EXIT.
7. **If no P0/P1:**
   - Append P2/P3 to `{{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md` (each item with origin workspace+task).
   - Write `output/review-report.md`: 7 dimensions, list of issues classified P0-P3, detected stops, final recommendation ("OK for 07" / "fix loop").
   - Follow Case A (gate-inline) in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

## Outputs

- `output/review-report.md` — 7-dimension report + P0-P3 classified issue list + detected stops + recommendation ("merge" or "fix loop").
- `output/p0-p1-issues.md` — only if P0/P1 exist; describes each issue with file, line, description, and proposed action for the fix wave.

## Sub_stage transitions

Valid enum: `06_in_progress`, `06_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/review-report.md` exists.
- No P0/P1 (otherwise, there is loopback to 04 — sub_stage returns to `04_wave_<N+1>_in_progress` and stage 06 will be revisited after).
- P2/P3 (if any) appended to `tech_debt.md`.
- Human approved via gate (status `COMPLETED_AWAITING_HUMAN` → human response).

**Loopback to 04 if P0/P1:** when reviewer classifies ≥1 issue as P0/P1, the sub_stage does NOT transition to `06_completed`. Instead, L1 is updated to `stage_atual: "04"` and `sub_stage: "04_wave_<N+1>_in_progress"` (or regeneration of the current wave). Stage 06 is revisited after the new wave passes through 05 verification — now with the issue fixed.

## Canonical statuses available in this stage

- `IN_PROGRESS` — active review, reviewer subagent running.
- `COMPLETED_AWAITING_HUMAN` — review-report ready without P0/P1, human approves before 07.
- `BLOCKED_STOP_POINT` — `over_eng`, `pii`, or `adr_drift` triggered; A/B/C menu awaiting response.
- `BLOCKED_ERROR` — verification-report absent, hook rejected commit, or reviewer subagent failed.

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. IDs triggerable in stage 06 review:

- `over_eng` — 3+ new abstraction layers without requirement (warning experimental/tool, hard development/production).
- `pii` — schema/logs with PII in plaintext (warning experimental, hard tool/development, hard+DPO production).
- `adr_drift` — delivered code diverges from active ADR without declared superseding.

Trigger: agent pauses, writes A/B/C menu in the output, updates L1 `status: BLOCKED_STOP_POINT`. Human responds, session resumes with `IN_PROGRESS`.

## Skill superpowers reference

200tok summaries (mandatory consultation by the reviewer subagent):

- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/requesting-code-review-200tok.md`
- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/receiving-code-review-200tok.md`

Formal skills (escape hatch): `superpowers:requesting-code-review`, `superpowers:receiving-code-review`.

## Gates

- **Human:** reviews `output/review-report.md`. If no P0/P1, approves "OK for 07?". If P0/P1, approves fix loop (automatic transition to 04).
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`.
- **Approval to transition:** human explicitly approves; sub_stage becomes `06_completed` in the commit that records the approval. Loopback to 04 does not require formal human gate — the reviewer classifying P0/P1 is sufficient; L1 transitions automatically.

## End of stage handoff (gate inline + 1-stage-1-session)

Stage 06 has two paths: loopback to 04 (automatic, no gate) and transition to 07 (with gate-inline). Bug v3.4.2 fixed only in Case A (transition to 07) — premature render+exit before approval created loop. Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

### Case A: handoff 06 → 07 (no P0/P1) — WITH human gate (gate inline)

#### Phase 1: WORK_DONE (after review-report.md written)

1. **Update L1**:
   - `sub_stage = 06_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 06_in_progress`
   - `last_transition.to = 06_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{event: "stage_transition", from: "06_in_progress", to: "06_completed", note: "work done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; **DO NOT** include `_kickoff.md`):
   ```
   workspace <NNN>: stage 06 work done, awaiting gate
   ```

3. **Print gate prompt** for human. Do NOT exit. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 06 (review) work COMPLETE — workspace <NNN-slug>
   No P0/P1 detected. Recommendation: OK for 07.

   Outputs ready for review:
     - <list of paths>

   L1: sub_stage=06_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review review-report.md (7 dimensions + P2/P3 in tech_debt).
   Reply in chat:
     - "approved" / "ok proceed to 07" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

#### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition):
   - `stage_atual = 07`
   - `sub_stage = 07_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 06_completed`
   - `last_transition.to = 07_in_progress`
   - `history` append: `{event: "stage_transition", from: "06_completed", to: "07_in_progress", note: "gate approved by human"}`

6. **Render `_kickoff.md`** in `<workspace>/stages/07_merge/_kickoff.md`.

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 07
   ```

8. **Print verbal KICKOFF block** for user:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 06 (review) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=07, sub_stage=07_in_progress, status=IN_PROGRESS
     - Kickoff: stages/07_merge/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 07 (merge).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/07_merge/CONTEXT.md
     workspaces/<NNN-slug>/stages/07_merge/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

9. **EXIT** the session.

#### Response "adjust X" / "abort"

- "adjust X": L1 status=IN_PROGRESS, history `gate_rejected`, return to review with request. Redo Phase 1 when outputs are ready again.
- "abort": L1 status=BLOCKED_ERROR, history `human_abort`. Commit + exit.

### Case B: loopback 06 → 04 (P0/P1 detected) — WITHOUT human gate

Loopback is auto-transition (per Gates section): reviewer classified P0/P1 → L1 transitions to 04 without formal human gate.

1. **Update L1**:
   - `stage_atual = 04`
   - `sub_stage = 04_wave_<N+1>_in_progress` (new fix wave) OR regeneration of current wave per severity
   - `status = IN_PROGRESS`
   - `last_transition.from = 06_in_progress`
   - `last_transition.to = 04_wave_<N+1>_in_progress`
   - `history` append: `{event: "stage_transition", from: "06_in_progress", to: "04_wave_<N+1>_in_progress", note: "fix loop — P0/P1 issues from review"}`

2. **Render `_kickoff.md`** in `<workspace>/stages/04_implementation_waves/_kickoff.md` (with `prev_outputs` including `p0-p1-issues.md` + fix loop note in `pending_for_this_stage`).

3. **Atomic commit** (outputs + L1 + kickoff):
   ```
   workspace <NNN>: stage 06 fix loop + kickoff wave <N+1>
   ```

4. **Print verbal KICKOFF block** + EXIT:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   🔁 Stage 06 LOOPBACK to 04 — P0/P1 detected — workspace <NNN-slug>
   Workspace updated at commit <sha>:
     - L1: stage_atual=04, sub_stage=04_wave_<N+1>_in_progress, status=IN_PROGRESS
     - Kickoff: stages/04_implementation_waves/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 04 (implementation_waves) — wave <N+1> fix.

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/04_implementation_waves/CONTEXT.md
     workspaces/<NNN-slug>/stages/04_implementation_waves/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```
