---
layer: L2
stage: "01"
stage_name: "discovery"
sub_stage_enum:
  - "01_in_progress"
  - "01_completed"
applicable_stop_points:
  - "stack"
  - "external_api"
  - "paid_service"
  - "pii"
output_files:
  - "output/discovery.md"
  - "_config/CONTEXT.md"
next_stage: "02"
---

# Stage 01 — discovery (L2)

Guided brainstorming with the human. Refines scope through iterative clarification, maps audience, functional and non-functional requirements, lists risks, and proposes macro options A/B/C for approach (without detailing architecture yet — that is stage 02). Defines MVP IN/OUT and success metrics. Output feeds design (stage 02) with a well-defined scope.

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/output/recon-report.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/.icm-main/docs/lessons.md | L3 | conditional: exists if inherited from stage 08 output C or prior iteration |
| 6 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/profile-effective.yaml | L3 | yes |
| 7 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/stop-points.md | L3 | yes |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/brainstorming-200tok.md | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |
| 12 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/test-recipes/{{PROFILE}}.md | L3 | conditional: exists if profile ∈ {app_web_backend, app_web_frontend, agent_ia, ml_project, cli_tool, framework_library, dashboard}. Read to inform §Test Context in discovery.md |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/ — discovery does NOT inspect source code. If code context is necessary, cite the dependency in recon-report and revisit 00.
- {{PROJECT_ROOT}}/.icm-main/tests/ — discovery does NOT read test code directly. It reads only the test index from recon-report.md (stage 00).
- {{PROJECT_ROOT}}/.icm-main/docs/decisions/ — detailed ADRs are consumed in stage 02. Here only the index already listed in recon-report.md is used.
- Outputs of stages 02+ — they do not exist yet.
- {{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md — tech debt scope appears in design (02), not in discovery.

## Process

1. **Pre-flight:** validate all Input paths marked `yes`; verify L1 `stage_atual: "01"` and `sub_stage: 01_in_progress` (read-only — do NOT change L1 here). If `recon-report.md` is absent → status `BLOCKED_ERROR` (recon needs to run first).
2. **Consult brainstorming 200tok summary** to standardize question format (A/B/C menu with recommendation, clarification questions before assuming).
3. **Iterative clarification with human:** target audience, objective, functional requirements (what it does), non-functional requirements (perf, security, scale), technical/budget constraints. Each non-trivial decision becomes an A/B/C menu with the agent's recommendation.
4. **Detect stop points during clarification:** if human describes integration with a paid SaaS, stack change, non-trivial external API, or PII handling → trigger the corresponding stop point per tier calibration in `_config/stop-points.md`.
5. **Map macro A/B/C options** for approach (high-level, without detailed architecture). Justify recommendation considering the profile/tier from `_config/profile-effective.yaml` (merged from L0 + local overrides).
6. **Define MVP IN/OUT:** what goes into this delivery vs what stays for later. Explicit list.
7. **List risks** (technical, scope, timeline) with proposed mitigation for each.
8. **Define success metrics** — how the human will know the MVP delivered value.
9. **Raise Test Context** — capture existing test information and team expectations:
   - Is there an existing test suite? Framework used? Estimated current coverage?
   - Is there a minimum coverage policy declared by the team?
   - Are there integration, e2e, or only unit tests?
   - For `agent_ia`/`ml_project`: is there an eval framework in use? How is non-deterministic output tested today?
   - Record conclusions in `discovery.md §Test Context`; absence of an answer → record "not raised" (stage 02 defines profile defaults).
   - If `_references/test-recipes/{{PROFILE}}.md` exists: consult it to contextualize questions to the human.
10. **Write `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/output/discovery.md`** with fixed sections: Executive summary (3-5 sentences); Target audience; Functional requirements; Non-functional requirements; Macro options A/B/C + choice; MVP IN/OUT; Risks and mitigations; Success metrics; **Test Context** (section 9 above); Triggered stop points (if any).
11. **End-of-stage handoff:** follow the gate-inline protocol in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

## Outputs

- `output/discovery.md` — refined scope: audience, requirements, chosen macro options, MVP IN/OUT, risks, metrics. If human disagrees with any item, they edit `output/discovery.md` directly. Do NOT overwrite their edits — they are the authority.

## Sub_stage transitions

Valid enum: `01_in_progress`, `01_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/discovery.md` exists with all fixed sections filled.
- Stop points triggered during the session are resolved (status returns to `IN_PROGRESS` before completing).
- Human approved via gate (status `COMPLETED_AWAITING_HUMAN` → human replies "approved, proceed to 02").

## Canonical statuses available in this stage

- `IN_PROGRESS` — active clarification with human.
- `COMPLETED_AWAITING_HUMAN` — discovery ready, human reviews/edits before transitioning.
- `BLOCKED_STOP_POINT` — A/B/C menu awaiting response (stack, external_api, paid_service, or pii).
- `BLOCKED_ERROR` — recon-report absent or required Input path failed.

## Applicable stop points

Canonical catalogue in `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md`. IDs triggerable in stage 01 discovery:

- `stack` — human describes a language/framework/runtime not yet declared in an ADR. Always `hard`.
- `external_api` — integration with an external API (paid? rate-limited? privacy?). Always `hard`.
- `paid_service` — recurring SaaS; threshold calibrated by tier (warning R$50 experimental / hard R$200 tool / hard R$500 development / hard R$1000 production).
- `pii` — handling of personal or sensitive data (LGPD); calibrated by tier (warning experimental / hard tool/development / hard+DPO production).

Trigger: agent pauses, writes A/B/C menu to `output/discovery.md § Stop points` (same as stage 00 convention), updates L1 `status: BLOCKED_STOP_POINT`. Human responds, session resumes with `IN_PROGRESS`. Non-architectural decisions stay noted in discovery.md; architectural ones propagate to 02 design (which may spawn an ADR).

## Skill superpowers reference

200tok summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/brainstorming-200tok.md`

Formal skill: `superpowers:brainstorming` (escape hatch — actual invocation only if discovery requires structured deep exploration beyond the summary).

## Gates

- **Human:** actively participates in clarification; reviews and approves `output/discovery.md`. Can edit directly if they disagree with any item.
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`.
- **Approval to transition:** human explicitly approves ("proceed to 02"); sub_stage becomes `01_completed` in the commit that records the approval. If a stop point is pending → do not transition.

## End of stage handoff (gate inline + 1-stage-1-session)

Handoff is split into TWO phases within the SAME session. Human gate sits between them — `_kickoff.md` is only rendered AFTER approval. Bug v3.4.2 fixed: premature render+exit before approval created loop "kickoff → user approves in new session → kickoff again". Canonical doc: `{{SKILL_DIR}}/references/session-handoff-protocol.md`.

### Phase 1: WORK_DONE (after outputs are ready)

1. **Update L1** (`{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md`):
   - `sub_stage = 01_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 01_in_progress`
   - `last_transition.to = 01_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "01_in_progress", to: "01_completed", commit_sha, note: "work done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; pre-commit hook validates atomicity):
   ```
   workspace <NNN>: stage 01 work done, awaiting gate
   ```
   Files: current stage outputs + L1. **DO NOT** include `_kickoff.md` (not rendered yet).

3. **Print gate prompt** for human. Do NOT exit the session. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 01 (discovery) work COMPLETE — workspace <NNN-slug>

   Outputs ready for review:
     - <list of paths>

   L1: sub_stage=01_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review the outputs above.
   Reply in chat:
     - "approved" / "ok proceed to 02" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition):
   - `stage_atual = 02`
   - `sub_stage = 02_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 01_completed`
   - `last_transition.to = 02_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "01_completed", to: "02_in_progress", commit_sha, note: "gate approved by human"}`

6. **Render `_kickoff.md`** in the next stage:
   - Path: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/_kickoff.md`
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render` or function `render_kickoff` from `{{SKILL_DIR}}/scripts/handoff.py`
   - **Script CLI reference:** `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/script-cli-reference.md` — exact format for `--prev-outputs`, `--pending`, and all other flags.
   - L4-kickoff YAML frontmatter per schema in `references/session-handoff-protocol.md`
   - Body: prev_outputs + prev_decisions + pending for next stage

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 02
   ```
   Files: next stage `_kickoff.md` + updated L1.

8. **Update project root CLAUDE.md dashboard:**
   ```bash
   python {{SKILL_DIR}}/scripts/handoff.py update-project-md \
       --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} \
       --profile {{PROFILE}} --tier {{TIER}} \
       --stage-atual 02 --stage-dir 02_design \
       --sub-stage 02_in_progress --status IN_PROGRESS \
       --skill-dir {{SKILL_DIR}}
   ```

9. **Print verbal KICKOFF block** for user (copy-paste for next session):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 01 (discovery) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=02, sub_stage=02_in_progress, status=IN_PROGRESS
     - Kickoff: stages/02_design/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 02 (design).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/02_design/CONTEXT.md
     workspaces/<NNN-slug>/stages/02_design/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

10. **EXIT** the session. Do NOT continue to the next stage in the same session.

### Response "adjust X" (gate rejected)

If human replies with free text requesting an adjustment:
- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected", note: "human requested adjustment: X"}`. Sub_stage stays `01_completed` (returns to `01_in_progress` if change is non-trivial).
- Return to work as requested.
- When outputs are redone, return to Phase 1 (new commit 1/2 + new gate prompt).

### Response "abort"

If human replies "abort":
- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort", note: "human aborted at gate"}`.
- Commit + exit. Workspace stays in BLOCKED_ERROR awaiting manual intervention.

---

## v3.3.0 references applicable to this stage

- **Ubiquitous Language (`_config/CONTEXT.md`):** stage 01 = grilling session.
  Each domain term resolved during discovery → update
  `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/CONTEXT.md` **inline** (glossary — NOT L1 `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md` state machine; do not batch at the end).
  Canonical format: `_references/runtime/context-format.md`.
- **Additional output:** glossary populated in `_config/CONTEXT.md` is a
  mandatory input for stage 02 (design).
