---
layer: L2
stage: "04"
stage_name: "implementation_waves"
sub_stage_enum:
  - "04_wave_<N>_in_progress"
  - "04_wave_<N>_completed"
sub_stage_pattern: "^04_wave_\\d+_(in_progress|completed)$"
applicable_stop_points:
  - "new_dep"
  - "irreversible"
  - "over_eng"
  - "prod_migration"
  - "adr_drift"
  - "ambiguous_feedback"
  - "design_system_cascade"
output_files:
  - "output/wave-<N>/task-<slug>.md"
  - "output/wave-<N>/wave-summary.md"
  - "output/wave-<N>/task-<slug>-blocked.md"
  - "output/wave-<N>/task-<slug>-critic-round<R>.json"
  - "output/wave-<N>/task-<slug>-diagnose.md"
  - "output/wave-<N>/task-<slug>-lead-decision.md"
next_stage: "05"
---

# Stage 04 — implementation_waves (L2)

Parallel execution in waves. Lead session orchestrates subagents via Agent tool respecting the cap per tier (2/3/5/5). Each subagent works on a task in isolated branch `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>` (from `{{BASE_BRANCH}}`), follows vertical TDD cycle (tracer-first + RED→GREEN→CI scope→REFACTOR loop). Per-task loop has cap 3 attempts, validated by L2 forensic+ extended (7 deterministic checks) + L3 orthogonal critic (Agent fresh context, anti-sycophancy, model = tier ceiling). When cap is exhausted OR convergence trip OR catastrophic detected → lead-resolution tier (3 buckets B1 REWRITE_SPEC / B3 DIRECT_IMPL / B4 VOID_TASK). Lead does sequential merge into `{{BASE_BRANCH}}` after approve. One sub_stage per wave: `04_wave_<N>_in_progress` → `04_wave_<N>_completed`. Repeats until `wave-plan.md` is exhausted.

**Consolidated canonical docs:**
- `references/wave-execution-protocol.md` — 14-step pipeline
- `references/critic-protocol.md` — L3 critic (v3.9.0)
- `references/lead-resolution-protocol.md` — buckets B1/B3/B4 (v3.9.0)
- `references/forensic-plus-protocol.md` — 8 checks (extended v3.10.0)
- `references/4-block-contract-template.md` — vertical TDD + tracer-first (v3.9.0)
- `references/mocking-guidelines.md` — boundaries only (v3.9.0)
- `references/script-cli-reference.md` — exact CLI format for all scripts (v3.12.1)

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/04_implementation_waves/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/wave-plan.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md | L4 | yes |
| 6 | {{PROJECT_ROOT}}/.icm-main/docs/decisions/ | L3 | conditional: read ONLY ADRs listed in "Applicable ADRs" of the task in plan.md |
| 7 | {{PROJECT_ROOT}}/.icm-main/docs/lessons.md | L3 | conditional: lessons-match.py pre-extracts relevant lessons; lead injects via channel 2 |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/test-driven-development-200tok.md | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/subagent-driven-development-200tok.md | L3 | yes |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/4-block-contract-template.md | L3 | yes |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/xp-conventions.md | L3 | yes |
| 12 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/stop-points.md | L3 | yes |
| 13 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/subagent-protocol.md | L3 | yes |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/04_implementation_waves/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 15 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 16 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |
| 17 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/critic-protocol.md | L3 | yes — L3 orthogonal critic (v3.9.0) |
| 18 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/lead-resolution-protocol.md | L3 | yes — buckets B1/B3/B4 (v3.9.0) |
| 19 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/forensic-plus-protocol.md | L3 | yes — 8 checks extended (v3.10.0) |
| 20 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/mocking-guidelines.md | L3 | yes — boundaries only (v3.9.0) |
| 21 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/e2e-coverage-protocol.md | L3 | yes — Check 8 + L4 wave gate e2e (v3.10.0) |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/workspaces/ (other workspaces — workspace isolation)
- ADRs in {{PROJECT_ROOT}}/.icm-main/docs/decisions/ NOT listed in "Applicable ADRs" of the current task
- Outputs of other stages in the same workspace (00, 01, 05+) — only plan.md (02) and wave-plan.md (03)
- {{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md directly — enters via lead's channel 2 if applicable

## Common protocol violations (READ FIRST — avoid these)

These are the most frequent lead mistakes observed across workspace sessions. Each costs
a retry cycle or a wasted wave.

| # | Violation | Consequence | Correct behavior |
|---|-----------|-------------|------------------|
| 1 | **Skipping L3 critic** — forensic or other script fails, lead proceeds without critic | Unreviewed code merges. Violates "always, all tiers" rule. | Fix root cause (branch name, missing commit, script bug). Never skip L3. If script crashes → `BLOCKED_ERROR`, diagnose, retry. |
| 2 | **No model selection** — all agents spawned with default model | Mechanical tasks waste tokens (haiku-capable task on opus). Architecture tasks under-modeled (opus-needed on sonnet). | Run `pick-model.py` per task in pre-flight. Set `model:` on every `Agent()` call. mechanical=haiku, integration=sonnet, architecture=opus. |
| 3 | **Merge from wrong branch** — merge executed from workspace branch, not main | Wrong base for merge commit. Confused history. | Always: `git checkout {{BASE_BRANCH}} && git merge --no-ff <branch>`. Verify with `git branch --show-current` before merge. |
| 4 | **Branch naming mismatch** — branch doesn't match `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>` | forensic-plus.py, lead-diagnose.py fail with "ambiguous argument" or "branch not found" | Use exact format: `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>`. Pre-flight verifies with `git branch --list`. |
| 5 | **Racing to execution** — skipping pre-flight because "3 root tasks, parallel, simple" | Hit errors mid-wave (script crash, wrong branch, wrong model). Cost > pre-flight cost. | Pre-flight checklist is mandatory. 30s verification saves 5-10min retry cycles. |
| 6 | **Parallel = simple assumption** — all root tasks spawned in parallel without verifying per-task preconditions | Blocked on first script error, agents idle, wasted spawns. | Verify forensic-plus callable + branch names correct BEFORE first Agent spawn. |

## Process

Each wave executes the pipeline below. `<N>` = current wave number.

1. **Lead pre-flight:** reads wave-plan.md; identifies current wave via L1 `waves.current`. Sub_stage transitions to `04_wave_<N>_in_progress`. Lead records in L1 history event `{event: "wave_started", wave: <N>, pre_wave_sha: <git rev-parse {{BASE_BRANCH}}>}` — used by ci-rollback-protocol.md as reset point.

   **Pre-flight verification checklist (MANDATORY — do NOT skip):**
   - [ ] `git checkout {{BASE_BRANCH}} && git branch --show-current` → confirms merge target is `{{BASE_BRANCH}}`
   - [ ] `git branch --list "wave-{{WORKSPACE_NUM}}-*"` → verify branch naming pattern matches `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>`
   - [ ] `python {{SKILL_DIR}}/scripts/forensic-plus.py --help` → script is callable (catches import errors early)
   - [ ] For each task: run `python {{SKILL_DIR}}/scripts/pick-model.py --plan <path> --task-slug <slug> --tier <tier> --output json` → records `writer_model` and `critic_model` per task
   - [ ] Model assigned per task: mechanical (scaffold/file I/O/subprocess) → `haiku`, integration (API/threading/GTK) → `sonnet`, architecture/orchestration → `opus`

2. **Lead spawns subagents via Agent tool:** for each task in the wave (up to cap):
   1. Lead creates branch BEFORE spawn: `git branch wave-{{WORKSPACE_NUM}}-<N>/<task-slug> {{BASE_BRANCH}}`. Lead stays on workspace branch (no checkout). Orphan branch (if Agent fails pre-checkout) detectable via `git branch --merged {{BASE_BRANCH}}` and cleaned up in step 11.
   2. Lead invokes `Agent(isolation: "worktree", subagent_type: "general-purpose", model: <writer_model>, description: "wave <N> task <slug>", prompt: <AGENT-BRIEF + channel-2>)`. `model` is set from pre-flight pick-model output (mechanical=haiku, integration=sonnet, architecture=opus). Harness does `git worktree add` pointing to the already-existing branch — does NOT create a new branch. Worktree path returned in Agent tool result; lead persists in local structure for later cleanup.
   3. Parallel tasks: multiple `Agent` calls in ONE message (multi tool-use). Sequential tasks (HITL or dependent): sequential calls.
3. **Lead injects channel 2:** injects into the subagent prompt only the subset of ADRs + critical lessons + extra conventions declared in plan.md for that task. Subagent does NOT read the project's global `docs/`. **If task has flag `requires_design_system: true`** (profile `app_web_frontend` or `fullstack`): lead also injects relevant DESIGN.md subset (applicable tokens + task's components section) — subagent reads via `Read {{PROJECT_ROOT}}/.icm-main/DESIGN.md` if it needs additional detail. Doc: `_references/runtime/design-system.md`.
4. **Subagent (CWD = project root, branch `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>`):** executes vertical TDD cycle (`references/4-block-contract-template.md` § 3):
   1. **Tracer-first** — writes 1 E2E golden path test (minimum viable, expected to be red). Commit as first of the task.
   2. **Loop per feature unit** (each iteration = 1 commit):
      - RED → 1 test (1 acceptance bullet OR edge case)
      - GREEN → minimal impl to make the test pass
      - CI scope → tests + types + lint on files touched (fast feedback)
      - REFACTOR → mandatory after every GREEN. Skip ONLY when all three Dirt Check questions (duplication, naming, function/file size — see `_config/xp-conventions.md`) answer NO.
   3. **Anti-horizontal slicing** — forbidden to write all tests at once OR all impl at once. Forensic+ Check 5 detects acceptance bullets without test mapping; if diff > 100 LOC without new test → stop and re-pace.
   4. **Commit verify gate** — before COMPLETE, confirm `git log --oneline {{BASE_BRANCH}}..HEAD` shows ≥1 commit. Zero = return to loop.
   5. **COMPLETE** — writes `output/wave-<N>/task-<slug>.md` minimalist (summary, modified files, tests, ADRs applied — NO inline Akita checklist, QA delegated to L2/L3).
5. **Stop points within the cycle:** if subagent detects `new_dep`, `irreversible`, `over_eng`, `prod_migration`, or `adr_drift` → pauses current state, writes A/B/C menu, returns signal to lead via Agent tool output, lead sets L1 `status: BLOCKED_STOP_POINT`. Human responds, cycle resumes from where it paused.
6. **Per-task QA loop** (cap 3 attempts):
   1. **L2 forensic+ extended** runs first (step 8b). HARD ≥ 1 → skip L3, surgical brief retry (does not waste tokens on code rejected by a cheap gate).
   2. **L3 orthogonal critic** (step 8c) always runs when L2 passed. REJECT → diagnose (step 8d) decides surgical retry OR escalate.
   3. **Cap 3 attempts** total. Exhausted → lead-resolution tier (step 9).
   4. **Convergence trip** (Jaccard ≥ 0.7 between rounds N and N-1) → immediate escalate without waiting for cap.
   5. **Catastrophic detected** (tests broken outside scope, globally broken build, scope creep > 5×) → immediate escalate bypassing cap.
7. **Lead receives each subagent's result via Agent tool:** lead waits for COMPLETE return from each subagent in the wave. Results arrive directly via Agent tool output — no directory polling. Return order is non-deterministic (parallelism). Lead bufferiza results in structure `{task_slug: agent_result}`. Before step 9 (sequential merge), lead orders tasks by index in `plan.md > tasks[]` of the current wave — merge order = ordem do plan, NOT return order. Auditable: `wave-summary.md` lists tasks in plan order.
8. **Wave-reviewer L2 + L3 (Agent sem worktree, sub-steps 8a-8e):**

   8a. **Pre-audit:** real files_touched (`git diff --name-only`) captured for all AFK tasks. Skip cross-task audit in 1-task wave (flag `skip_cross_task_audit: true` in wave-plan.md).

   8b. **L2 Forensic+ extended (8 checks, deterministic, 0 token):** for each AFK task in the wave (skip `type: HITL`), reviewer Agent invokes:
       ```bash
       python {{SKILL_DIR}}/scripts/forensic-plus.py \
           --workspace-num {{WORKSPACE_NUM}} --wave <N> --task-slug <slug> \
           --base-branch {{BASE_BRANCH}} --tier <T> \
           --plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md \
           --output json
       ```
       Parse JSON. Record in `output/wave-<N>/task-<slug>.md` frontmatter fields `forensic_violations`, `forensic_passed`, `forensic_max_severity`, `forensic_respawn_count`. Canonical doc: `references/forensic-plus-protocol.md`. Script crash (exit 1) → reviewer emits `forensic_error` + treats as HARD; lead → `BLOCKED_ERROR error_type: forensic_script_crash`.

       - HARD in ≥1 check → skip 8c (do not run L3 on code rejected by cheap gate), surgical brief for retry. Per-task cap = 3 attempts; forensic-plus internal cap `MAX_FORENSIC_RETRIES = 2` (hardcoded in scripts/forensic-plus.py — drift-checked) is semantically equivalent (3 attempts total = 1 original + 2 retries). Exhausted → escalate lead-resolution.

   8c. **L3 Orthogonal Critic (always, all tiers — v3.9.0):** for each AFK task that passed 8b, lead renders critic prompt then invokes critic via Agent tool with fresh context:

       1. **Render critic prompt** (automated — script captures diff + test output):
          ```bash
          python {{SKILL_DIR}}/scripts/render-critic-prompt.py \
              --task-slug <slug> --wave <N> --tier <TIER> \
              --workspace-num {{WORKSPACE_NUM}} --base-branch {{BASE_BRANCH}} \
              --plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md \
              --critic-model <critic_model_from_pick_model_py> \
              --output output/wave-<N>/task-<slug>-critic-prompt-round<R>.md
          ```
       2. **Spawn critic** with the rendered prompt:
          ```python
          Agent(
              description="L3 critic task <slug> wave <N>",
              subagent_type="general-purpose",
              model=<critic_model_from_pick_model_py>,  # = TIER_CEILING[tier]
              prompt=Read("output/wave-<N>/task-<slug>-critic-prompt-round<R>.md"),
          )
          ```
       Critic output JSON triplet (claim, evidence file:line, counterexample, severity BLOCKING|MAJOR|MINOR; decision APPROVE|REJECT|ABSTAIN). Canonical doc: `references/critic-protocol.md`. Critic JSON saved in `output/wave-<N>/task-<slug>-critic-round<R>.json` (R = attempt number 1-3).

       - REJECT (≥1 BLOCKING or ≥2 MAJOR) → 8d diagnose.
       - ABSTAIN → treated as REJECT; 2 consecutive ABSTAIN → `BLOCKED_ERROR error_type: critic_abstain_loop`.
       - APPROVE → task PASS, proceed to step 10 merge.

   8d. **Diagnose (deterministic, 0 token):** when 8b HARD OR 8c REJECT, lead invokes:
       ```bash
       python {{SKILL_DIR}}/scripts/lead-diagnose.py \
           --task-slug <slug> --wave <N> --workspace-num {{WORKSPACE_NUM}} \
           --base-branch {{BASE_BRANCH}} \
           --critic-rounds output/wave-<N>/task-<slug>-critic-round1.json[,round2.json,...] \
           --files-touched <comma-sep from step 8a: `git diff --name-only {{BASE_BRANCH}}...wave-{{WORKSPACE_NUM}}-<N>/<slug>`> \
           --forensic-files-outside <int from 8b Check 2> \
           --output output/wave-<N>/task-<slug>-diagnose.md
       ```
       Renders diagnose.md with trigger condition (T1/T2/T3) + Jaccard table + catastrophic signals + bucket recommendation (B1/B3/B4) + surgical brief (if B1).

   8e. **Decision per task:**
       - **Cap not exhausted AND not convergence AND not catastrophic** → surgical retry: lead re-spawns writer with concise brief (top-3 concerns + acceptance delta from critic triplets). Return to step 4. Attempt counter ++.
       - **Cap 3 exhausted OR convergence trip OR catastrophic** → escalate lead-resolution tier (step 9).
       - **Only SOFT in 8b + APPROVE in 8c** → `approved_pending_ci: true`, warnings logged in `wave-summary.md` § L2/L3 summary. Merge proceeds (step 10).

9. **Lead-resolution tier (B1/B3/B4) — when step 8 escalated:**
   Lead reads `output/wave-<N>/task-<slug>-diagnose.md` recommended bucket. Lead may override ONLY with explicit justification recorded in `output/wave-<N>/task-<slug>-lead-decision.md` (schema: `diagnose_recommended`, `lead_chose`, `rationale` — MUST explain why override). Override without documented rationale = `BLOCKED_ERROR error_type: lead_override_unjustified`. L1 status: `LEAD_RESOLUTION_IN_PROGRESS`. Canonical doc: `references/lead-resolution-protocol.md`.

   - **B1 REWRITE_SPEC:** lead rewrites task in plan.md (VALIDATION more specific, additional OUT OF SCOPE, prescriptive HOW). Commit plan update. 1 final writer spawn with new brief. Output passes L2+L3 (return to step 8). APPROVE → merge. REJECT → escalate B3.
   - **B3 DIRECT_IMPL:** lead writes code directly in branch `wave-<NNN>-<N>/<slug>-lead-resolved`. Same vertical TDD cycle. Output passes L2+L3 same as normal writer (return to step 8). APPROVE → merge. REJECT → escalate B4.
   - **B4 VOID_TASK:** lead rewrites task with VOIDED block (MUST include all 3 fields):
     ```markdown
     ### VOIDED — wave <N> attempt <date>
     - Reason: <ADR conflict | scope invalid | upstream blocker | other>
     - Evidence: <file:line OR critic concern OR external constraint>
     - Action proposed: <new task slug OR defer to v.NEXT OR remove from scope>
     ```
     Commit plan update. Trigger `wave-planner-script.py --recalculate` re-derives DAG without task. Wave continues with remaining tasks. L1 history append `event: task_voided`.

   Cap: 1 attempt per bucket per task. Sequence B1→B3→B4. Skipping a bucket is OK; revisiting a used bucket is forbidden. All exhausted → `BLOCKED_ERROR error_type: lead_resolution_all_buckets_failed`.

10. **Sequential merge:** lead merges each branch `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>` (OR `-lead-resolved` when B3) into `{{BASE_BRANCH}}` using the buffered order from step 7 (= plan order). Command: `git checkout {{BASE_BRANCH}} && git merge --no-ff <branch>` per task. `--no-ff` preserves commit group (auditable). **Merge conflict → STOP — NEVER resolve autonomously.** Merge code is high risk. Follow `references/conflict-resolution-protocol.md`: human must decide (rebase/abort/manual resolution). Autonomous merge conflict resolution = `BLOCKED_ERROR`.
11. **L4 wave gate (CI global + E2E + coherence):** sub-gates after all merges:

    11a. **CI global green** (always, all tiers) — runs the project's full CI. Red → `references/ci-rollback-protocol.md`.
    11b. **E2E suite green** (v3.10.0, tier dev/prod with non-empty `user_facing_paths` in profile) — runs E2E suite via `_config/profile-effective.yaml:e2e.e2e_command` (default lookup `npm run test:e2e`/`pnpm test:e2e`/`pytest tests/e2e/`). Red → `BLOCKED_ERROR error_type: e2e_suite_failed` → diagnose protocol → human gate A/B/C. Skip when profile has `user_facing_paths: []` (data_analysis, technical_article, experiment) OR tier exp/tool without declared `e2e_command`.
    11c. **Cross-task coherence** (production tier, ≥2 tasks sharing file/API change) — subagent fresh context, mandatory v3.12.1. Skip only when tier < production OR all tasks in wave touch disjoint file sets with no shared APIs. Canonical doc: `references/e2e-coverage-protocol.md`.

    Canonical doc for E2E reinforcement: `references/e2e-coverage-protocol.md`.
12. **Cleanup wave worktrees + branches (v3.4.3):** after successful merge + green CI, lead removes ephemeral worktrees created by subagents AND deletes already-merged branches. Bug pre-v3.4.3: worktrees in `<project_root>/.icm-wave-*` (or path returned by Agent tool) were orphaned after each wave; branches `wave-<NNN>-<N>/<task-slug>` polluted `git branch` listing.

   ```bash
   # For each task in the wave (paths captured from Agent tool results):
   git worktree remove <path-to-worktree>           # removes ephemeral worktree
   git branch -d wave-{{WORKSPACE_NUM}}-<N>/<task-slug>   # safe: already merged --no-ff

   # Robust fallback (if path was lost — search by branch pattern):
   git worktree list --porcelain | awk '/^worktree /{p=$2} /^branch refs\/heads\/wave-{{WORKSPACE_NUM}}-<N>/{print p}' \
     | xargs -I {} git worktree remove {}
   ```

   **Decision matrix `--force`:**
   - `git worktree remove <path>` fails if working tree is not clean → lead reads task report `output/wave-<N>/task-<slug>.md`:
     - L2 + L3 PASS in frontmatter (`forensic_passed: true` AND `critic_decision: APPROVE`) → safe to use `git worktree remove --force <path>` (orphan lock file is the only remaining cause).
     - Otherwise → do NOT force. Set `status: BLOCKED_ERROR`, record in `wave-summary.md`, human inspects manually.
   - `git branch -d` refuses if not merged → NEVER use `-D`. Non-merged branch after merge step indicates a bug in sequential merge; investigate first.
   - Non-fatal cleanup failure (after valid force): record warning in `wave-summary.md` (next step).

13. **Lead writes:** `output/wave-<N>/wave-summary.md` (completed tasks, conflicts, decisions made, **cleanup warnings** if any, **§ L2/L3 summary** with SOFT violations + critic MINOR concerns, **§ Lead resolutions** with bucket table applied if any).
14. **End-of-wave/stage handoff:** follow protocol in the `## End of stage handoff` section of this L2. Mid-wave (wave <N> → <N+1>): automatic handoff without human gate (Case A). Last wave → stage 05: mandatory gate-inline (Case B — Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

CWD: lead at `{{PROJECT_ROOT}}` (workspace branch). Subagent at `{{PROJECT_ROOT}}` on branch `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>`.

## Outputs

- `output/wave-<N>/task-<slug>.md` — task report from subagent (summary, Auto-QA Akita 15-items, cycles consumed).
- `output/wave-<N>/wave-summary.md` — lead synthesis post wave-reviewer + merge.
- `output/wave-<N>/task-<slug>-blocked.md` — conditional: MUST be written when subagent triggers stop point or exhausts 3-attempt cap. Contains stop point ID, A/B/C menu presented, human choice, and resolution.

## Sub_stage transitions

Valid enum: `04_wave_<N>_in_progress`, `04_wave_<N>_completed` (`<N>` positive integer). Pattern: `^04_wave_\d+_(in_progress|completed)$`.

`04_wave_<N>_in_progress` → `04_wave_<N>_completed` transition fires when:
- All subagents in the wave delivered `task-<slug>.md` COMPLETE.
- Wave-reviewer approved.
- Sequential merge green + global CI green.
- `wave-summary.md` written.

`04_wave_<N>_completed` → `04_wave_<N+1>_in_progress` (if more waves remain) is internal to the stage. Last wave → `next_stage: 05`.

## Canonical statuses available in this stage

- `IN_PROGRESS` — wave executing (lead orchestrating, subagents working).
- `COMPLETED_AWAITING_HUMAN` — last wave completed, waiting for human to approve transition to 05.
- `BLOCKED_STOP_POINT` — subagent triggered A/B/C menu; human responds.
- `BLOCKED_ERROR` — merge conflict, global CI red, cap 3 attempts exhausted + B1+B3+B4 all failed, critic abstain loop, OR cleanup --force unsafe.
- `BLOCKED_HITL` — mixed wave with 1+ task `type: HITL` awaiting human (not a failure; external wait).
- `LEAD_RESOLUTION_IN_PROGRESS` (v3.9.0) — per-task loop exhausted trigger condition (cap 3 / convergence trip / catastrophic); lead executing bucket B1/B3/B4. Sub_stage stays `04_wave_<N>_in_progress`.

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. IDs triggerable in stage 04:

- `new_dep` — new npm/pip/cargo dependency added during implementation that was not in plan.md.
- `irreversible` — `DROP TABLE`, `git push --force`, hard-delete without prior soft-delete.
- `over_eng` — 3+ new abstraction layers without requirement (calibrated: warning experimental/tool, hard development/production).
- `prod_migration` — migration touches a production-volume table without an agreed maintenance window.
- `adr_drift` — implementation diverges from active ADR without declared superseding.
- `ambiguous_feedback` — (preview loop v3.6.0) human visual feedback with low confidence: vague description, screenshot without clear annotation, contradiction between text and visual. Always `hard`.
- `design_system_cascade` — (preview loop v3.6.0) token change affects > `preview_loop.design_cascade_threshold` components. Always `hard`.

## Skill superpowers reference

TDD summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/test-driven-development-200tok.md`

Subagent summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/subagent-driven-development-200tok.md`

Formal skills: `superpowers:test-driven-development` + `superpowers:subagent-driven-development` (escape hatch).

## Gates

- **Human:** approves last wave transition to stage 05; responds to A/B/C stop point menus; resolves merge conflicts when they occur.
- **Automatic (CI):** commit-msg hook validates prefix `workspace {{WORKSPACE_NUM}}:` on workspace branch (R6); wave branches and base branch use Conventional Commits (`feat:`, `fix:`, etc.) without hook validation; global CI runs after each wave merge; Auto-QA Akita validated by wave-reviewer.
- **Approval to transition:** wave closes automatically when merge + global CI green + wave-summary written. Last wave needs explicit human approval to transition to stage 05.

## End of stage handoff (gate inline + 1-stage-1-session, wave-aware)

**Stage 04 exception (wave-aware):** each wave = 1 lead session. Lead closes wave generating kickoff for the next wave (same stage 04, sub_stage `04_wave_<N+1>_in_progress`) OR for stage 05 (after last wave). Sub-waves (subdivisions within a wave) do NOT trigger kickoff — lead persists through sub-waves within the same session.

### Case A: mid-wave handoff (wave <N> → wave <N+1>) — WITHOUT human gate

Mid-wave handoff is automatic (no gate) when merge + global CI green + wave-summary written. Bug v3.4.2 does not affect this path — intermediate wave has no human gate by design (gate only at transition to 05).

1. **Update L1**:
   - `sub_stage = 04_wave_<N+1>_in_progress` (immediate transition, without persisting `04_wave_<N>_completed` in status)
   - `status = IN_PROGRESS`
   - `last_transition.from = 04_wave_<N>_in_progress`
   - `last_transition.to = 04_wave_<N+1>_in_progress`
   - `history` append: 2 events (`wave_completed` + `stage_transition`)

2. **Render `_kickoff.md`** in `<workspace>/stages/04_implementation_waves/_kickoff.md` (overwrite — `wave_target` in body points to wave <N+1>).

3. **Atomic commit** (outputs + L1 + kickoff):
   ```
   workspace <NNN>: wave <N> complete + kickoff wave <N+1>
   ```

4. **Print verbal KICKOFF block** for user (copy-paste). EXIT the session.

### Case B: last wave handoff → stage 05 — WITH human gate (gate inline)

After last wave completed, human gate is MANDATORY before transitioning to 05. Bug v3.4.2 fixed here: premature render+exit before approval created loop "kickoff → user approves in new session → kickoff again". Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

#### Phase 1: WORK_DONE (after last wave merged + global CI green)

1. **Update L1**:
   - `sub_stage = 04_wave_<N>_completed` (N = last wave)
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 04_wave_<N>_in_progress`
   - `last_transition.to = 04_wave_<N>_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{event: "wave_completed", note: "last wave, awaiting gate"}`

2. **Atomic commit 1/2** (wave outputs + L1; **DO NOT** include `_kickoff.md`):
   ```
   workspace <NNN>: stage 04 work done (last wave), awaiting gate
   ```

3. **Print gate prompt** for human. Do NOT exit. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 04 (implementation_waves) work COMPLETE — workspace <NNN-slug>
   Last wave (<N>) merged + global CI green.

   Outputs ready for review:
     - <task reports + wave-summary>

   L1: sub_stage=04_wave_<N>_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review wave-summary + task reports.
   Reply in chat:
     - "approved" / "ok proceed to 05" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

#### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition):
   - `stage_atual = 05`
   - `sub_stage = 05_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 04_wave_<N>_completed`
   - `last_transition.to = 05_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{event: "stage_transition", from: "04_wave_<N>_completed", to: "05_in_progress", note: "gate approved by human"}`

6. **Render `_kickoff.md`** in `<workspace>/stages/05_verification/_kickoff.md`.

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 05
   ```

8. **Print verbal KICKOFF block** for user (copy-paste for next session):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 04 (implementation_waves) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=05, sub_stage=05_in_progress, status=IN_PROGRESS
     - Kickoff: stages/05_verification/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 05 (verification).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/05_verification/CONTEXT.md
     workspaces/<NNN-slug>/stages/05_verification/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

9. **EXIT** the session.

#### Response "adjust X" (gate rejected)

- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected"}`. Sub_stage stays `04_wave_<N>_completed`.
- Return to work as requested. May involve re-spawning subagents or direct correction.
- When outputs are redone, return to Phase 1.

#### Response "abort"

- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort"}`. Commit + exit.

---

## References applicable to this stage (v3.3.0+, consolidated through v3.12.1)

- **AGENT-BRIEF (`_references/runtime/agent-brief-template.md` +
  `<skill_root>/scripts/agent-brief-render.py`):** lead session generates
  structured brief per task BEFORE spawning Agent tool. CLI:

  ```bash
  python {{SKILL_DIR}}/scripts/agent-brief-render.py \
      --task <slug> \
      --plan stages/02_design/output/plan.md \
      --adrs {{PROJECT_ROOT}}/.icm-main/docs/decisions
  ```

  Output (markdown) is injected into the Agent tool prompt. Anti-patterns
  (absolute paths, line numbers) generate warnings.

- **Subagent worktree (v3.4.0):** lead spawns subagents via
  `Agent(isolation: "worktree")` for wave branches `wave-{{WORKSPACE_NUM}}-<N>/<task-slug>`
  derived from `{{BASE_BRANCH}}`. Tool creates ephemeral worktree; subagent
  works in it isolated from the main worktree (which remains on
  `workspace/{{WORKSPACE}}`). Lead stays at `{{PROJECT_ROOT}}/`
  workspace branch throughout the wave. After subagent finishes, lead
  inspects the returned worktree result and merges the wave branch into
  `{{BASE_BRANCH}}` per the stage 04 protocol.

  **Sync `.icm-main` (conditional v3.5.0):** after merge, lead checks if
  `{{PROJECT_ROOT}}/.icm-main` exists AND is a linked worktree:
  ```bash
  if git worktree list --porcelain | grep -q "worktree {{PROJECT_ROOT}}/.icm-main"; then
      cd {{PROJECT_ROOT}}/.icm-main && git pull --ff-only
  fi
  ```
  If absent: silent skip (`.icm-main` is an optional convention set up
  by recovery wizard / bootstrap in some workspaces). Failure of
  `pull --ff-only` (e.g., divergence): non-fatal warning in
  `wave-summary.md`, lead continues.

- **HITL handling (task-level granularity):**
  - **Wave-level HITL** (all tasks in the wave have `type: HITL`, or
    wave-planner isolated HITL tasks in sub-wave cap=1): lead does NOT spawn
    Agent for any task. Generates AGENT-BRIEF for each, displays to human,
    updates L1 `status=COMPLETED_AWAITING_HUMAN,
    sub_stage=04_wave_N_hitl_pending`, EXIT. Next session (after human
    resolves) reads task reports filled by human and proceeds.
  - **Task-level HITL** (mixed wave — some tasks `type: HITL`, others
    not): lead spawns Agents for non-HITL tasks IN PARALLEL; for each
    HITL task generates AGENT-BRIEF + writes `output/wave-<N>/task-<slug>.md`
    with frontmatter `status: AWAITING_HITL` + inline brief. Lead waits
    for non-HITL Agents to return. After return: if there are still tasks
    AWAITING_HITL, lead updates L1 `status=BLOCKED_HITL,
    sub_stage=04_wave_N_partial_hitl_pending`, EXIT. Next session
    validates that HITL tasks became `status: COMPLETE` (human edited) and
    resumes step 8 (wave-reviewer) with the entire wave.
  - New canonical status: `BLOCKED_HITL` (distinct from `BLOCKED_ERROR` —
    not a failure, it is external waiting).

- **Diagnose protocol note (`_references/runtime/diagnose-protocol.md`):**
  subagent that detects a recurring bug in its task MAY activate diagnose
  protocol (build feedback loop → reproduce → hypothesise → fix) before
  declaring BLOCKED. Report result in `task-<slug>.md`.

## Preview Loop entry/exit hooks (v3.6.0)

Applies ONLY when effective profile has
`preview_loop.preview_loop_enabled: true` (read from
`_config/profile-effective.yaml`). Canonical doc:
`_references/runtime/preview-loop-protocol.md`.

### Entry hook (1st session of wave 1, OR fresh session of wave>1)

Lead executes BEFORE step 1 (pre-flight) above:

1. **Detect package manager** via lockfile in `{{PROJECT_ROOT}}`:
   - `bun.lockb` or `bun.lock` → `bun dev`
   - `pnpm-lock.yaml` → `pnpm dev`
   - `yarn.lock` → `yarn dev`
   - `package-lock.json` → `npm run dev`
   - Multiple: priority `bun > pnpm > yarn > npm`.
   - None: stop point `BLOCKED_ERROR` — missing initial scaffold (should
     have been created in wave 1 task 1).

2. **Verify runtime registry** (v3.7.0):
   ```bash
   python {{SKILL_DIR}}/scripts/runtime-registry.py list \
       --workspace-root {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}} \
       --kind dev_server
   ```
   - Entry with alive PID → reuse, skip start.
   - Entry with dead PID → unregister (stale registry; auto-recovery via
     `recovery-wizard.py` `RUNTIME_REGISTRY_STALE`).
   - No entries → start new (step 3).

   **Legacy (v3.6.0):** if workspace was created pre-v3.7.0 and has
   `.icm-main/.dev-server.pid` instead of the registry, run
   `migrate-workspace.py --workspace-root <ws>` BEFORE proceeding.

3. **Start dev server in background + register:**
   ```bash
   cd {{PROJECT_ROOT}}
   <pm> run dev > .icm-main/.dev-server.log 2>&1 &
   PID=$!
   python {{SKILL_DIR}}/scripts/runtime-registry.py register \
       --workspace-root {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}} \
       --kind dev_server --pid $PID --port <PORT> --command "<pm> run dev"
   ```
   Wait 3-5s for Vite/Next to boot (read stderr from log until "ready"
   or "Local:" appears). Failure = `BLOCKED_ERROR`.

   **Custom dev server** (non-default): register with appropriate kind
   (`background_task` if daemon worker, etc.) with extra `--metadata`. Doc:
   `_references/runtime/runtime-cleanup-protocol.md`.

4. **Print kickoff priming** to human:

   ```
   🎨 Preview loop active — workspace {{WORKSPACE}}

   Dev server: http://localhost:3000 (PID <pid>)
   Chrome CDP helper: scripts/launch-chrome-cdp.{bat,sh}
   Preview pages: localhost:3000/preview/<component>

   For visual feedback, any combo works:
     - Text: "right button, more padding"
     - Annotated screenshot (Win+Shift+S Snipping or ShareX): paste PNG
     - URL: "/checkout, header misaligned"
     - HTML: paste outerHTML of the problematic element

   If ambiguous, I'll ask before making changes (stop point ambiguous_feedback).
   ```

### Tier-aware verification during implementation

Replace/complement Auto-QA Akita from step 4.6:

- **Each Edit** in a `.ts/.tsx/.vue/.svelte` file → subagent runs
  `tsc --noEmit` (~1s). Failure = do NOT declare task done, immediate fix.
- **Wave end** (after step 9 merge) → lead runs full lint + headless Playwright
  sample-check (1 click on each new component in the wave, validates render
  without crash).
- **On human request** ("ok test" / "validate") → lead runs full suite +
  relevant e2e.
- **Always active:** native Vite/Next overlay shows compile errors
  on the human's screen directly.

### New stop point: `ambiguous_feedback`

Triggerable during the wave when human gives visual feedback with low
confidence (vague description, screenshot without clear annotation, contradiction
between text and visual). Lead/subagent does NOT speculate and make changes: pause,
write A/B/C menu with candidate interpretations, update L1
`status: BLOCKED_STOP_POINT`. Calibration: always `hard` (any tier).

### New stop point: `design_system_cascade`

Triggerable when a token change affects > `preview_loop.design_cascade_threshold`
(default 5) components. Menu A/B/C: global cascade / limit scope /
cancel. Always `hard`.

### Exit hook (final stage 04 handoff — Case B Phase 2 GATE_APPROVED)

Lead executes AFTER commit 2/2 of the approved gate (Case B step 7), before
printing the KICKOFF block.

**v3.7.0 (registry-based):**

1. **List dev_server entries** from registry:
   ```bash
   python {{SKILL_DIR}}/scripts/runtime-registry.py list \
       --workspace-root {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}} \
       --kind dev_server --format json
   ```
2. **For each entry with alive PID**, kill the process:
   - POSIX: `kill <pid>` (or `kill -9 <pid>` if unresponsive).
   - Windows: `taskkill /PID <pid> /F`.
   Silent failure is OK (process already dead).
3. **Unregister entries** (regardless of PID alive/dead):
   ```bash
   python {{SKILL_DIR}}/scripts/runtime-registry.py unregister \
       --workspace-root {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}} \
       --id <entry_id>
   ```
   Or batch via `purge-dead` if all PIDs already dead.
4. **Delete `.dev-server.log`** (housekeeping).
5. **Do NOT delete** `.icm-chrome-profile/` — human may want to keep
   tabs open for next workspace; recovery wizard cleans up when
   it detects a persistent orphan.

Stage 05 (verification) does NOT depend on the dev server. Stage 06+ likewise.

**Legacy (v3.6.0):** pre-v3.7.0 workspaces still use
`.icm-main/.dev-server.pid` directly. Migration via
`migrate-workspace.py` moves to registry. After migration, this exit hook
works uniformly.
