---
layer: L2
stage: "05"
stage_name: "verification"
sub_stage_enum:
  - "05_in_progress"
  - "05_completed"
applicable_stop_points: []
output_files:
  - "output/verification-report.md"
next_stage: "06"
---

# Stage 05 — verification (L2)

Technical audit of what was delivered in stage 04. No new code. Verifies that outputs declared in `plan.md` and `wave-plan.md` exist in the FS, runs global CI locally (or consults status), and does a sample-check of 3 random ADRs — verifies they were cited in ≥1 task report. CI failure becomes `BLOCKED_ERROR` (not a stop point — verification is deterministic like the wave-planner).

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/05_verification/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/wave-plan.md | L4 | yes |
| 6 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/04_implementation_waves/output/ | L4 | yes |
| 7 | {{PROJECT_ROOT}}/.icm-main/docs/decisions/ | L3 | yes — sample-check (3 random ADRs) |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/verification-before-completion-200tok.md | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/xp-conventions.md | L3 | yes |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/05_verification/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 12 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |
| 13 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/lead-resolution-protocol.md | L3 | yes — meta-check of bucket audit (v3.9.0) |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/e2e-coverage-protocol.md | L3 | yes — audit E2E suite freshness (v3.10.0) |

## Não Lê (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/ (source code; CI already compiled/linted/type-checked)
- {{PROJECT_ROOT}}/.icm-main/tests/ — exception: coverage report and list of existing test files are verified in steps 4.5 and 4.6 below via `git ls-files` + CI coverage, without reading test content
- Outputs of stages 00, 01, 06+ of the same workspace
- {{PROJECT_ROOT}}/.icm-main/docs/lessons.md, {{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md (scope of stage 06 review)

## Process

1. Pre-flight: validate Input paths exist; sub_stage `05_in_progress`.
2. **List declared deliverables:** parse plan.md per task → `Files touched` + documentary outputs. Join with tasks executed in wave-plan.md.
3. **Verify FS existence:** for each declared file, check `git ls-files` in `{{BASE_BRANCH}}` post-wave merges (or in workspace branch + rebased waves). Diff delivered vs declared.
4. **Run global CI locally** OR consult remote CI status if available. Capture: lint, type-check, tests, coverage.
4.5 **Audit coverage:** read coverage report generated by CI (file `coverage.xml`, `.coverage`, `lcov.info`, `coverage/coverage-summary.json`, or equivalent — location declared in `plan.md §Test Strategy`). Extract coverage % of lines/branches. Compare with `test_specs.coverage_threshold` from `_config/profile-effective.yaml`. Result:
   - ≥ threshold → PASS for this item.
   - < threshold AND tier ∈ {experimental, tool} → CONDITIONAL (warning in report, does not block).
   - < threshold AND tier ∈ {development, production} → FAIL (blocks transition to stage 06; status `BLOCKED_ERROR`).
   - Coverage report absent AND `tdd_required: true` → FAIL.
4.6 **Sample-check test types:** select 3 random tasks from `wave-plan.md`. For each:
   - Verify that test files declared in `Files touched` in `plan.md` exist in FS via `git ls-files`.
   - Verify that the test type (unit/integration/e2e/component/eval) matches `test_specs.test_types_required` from the effective profile.
   - Record in report: task slug, expected file, found file (✅/⚠️), declared test type vs found.
   - ≥2/3 tasks with correct files → PASS; 1/3 → CONDITIONAL; 0/3 → FAIL.
4.7 **Audit E2E suite (v3.10.0):** when profile tier dev/prod with non-empty `user_facing_paths`:
   - Locate e2e suite via `_config/profile-effective.yaml:e2e.e2e_suite_root` (default tries `e2e/`, `cypress/`, `tests/e2e/` in order).
   - Verify suite exists and has ≥1 spec file. Absent → `BLOCKED_ERROR error_type: e2e_suite_missing`.
   - Verify last modification of specs in git: `git log -1 --format=%ct -- <e2e_suite_root>`. Stale = > 7 days AND wave-summary shows ≥1 task `Requires E2E update: true` delivered in the current wave. Stale → `BLOCKED_ERROR error_type: e2e_suite_stale`.
   - Audit CI report (step 4) extracted e2e result — green OR yellow (CONDITIONAL) accepted; red = FAIL.
   - Audit tasks with `**E2E:** skip` in plan.md must have rationale after `-`. Vague (absent OR < 5 chars) → `BLOCKED_ERROR error_type: e2e_skip_unjustified`.

   Skip entirely when profile has `user_facing_paths: []` (data_analysis, technical_article, experiment). Canonical doc: `references/e2e-coverage-protocol.md`.

5. **Sample-check ADRs:** select 3 random ADRs from `{{PROJECT_ROOT}}/.icm-main/docs/decisions/`. For each, `grep` in directory `stages/04/output/` for a mention (ADR slug or number). ≥1 mention = ok; 0 mentions = warning in report.
5.5 **Audit lead resolutions (v3.9.0):** read `stages/04/output/wave-*/wave-summary.md` and extract section `## Lead resolutions` (table with bucket applied per voided/resolved task). For each entry, apply deterministic meta-check:
   - **B1 (REWRITE_SPEC):** compare plan.md task before vs after rewrite. Spec rewrite must TIGHTEN (more specific VALIDAÇÃO bullets OR more NÃO QUERO bullets). LOOSEN (removing criteria) without evidence in diagnose.md → FAIL.
   - **B3 (DIRECT_IMPL):** read critic concerns accumulated in `task-<slug>-critic-round*.json`. Lead diff in branch `-lead-resolved` must address real concerns (heuristic: BLOCKING claims in concerns must appear as files_modified OR test names in lead diff). Lead that merely silenced critic without fix → FAIL.
   - **B4 (VOID_TASK):** read block `### VOIDED` in plan.md. Rationale must cite concrete ADR conflict OR concrete upstream blocker. Vague reason ("complexity too high", "out of scope") without evidence → FAIL.

   Audit is regex+structure (zero LLM cost). FAIL → `BLOCKED_ERROR error_type: lead_resolution_audit_failed`. Canonical doc: `references/lead-resolution-protocol.md` § Audit trail (consumed stage 05).
6. **Write `output/verification-report.md`:** sections `Deliverables (declared vs delivered)`, `CI Status`, `Sample ADRs`, `Lead resolutions audit` (v3.9.0), `Summary PASS/CONDITIONAL/FAIL`.
7. If global CI failed OR deliverables absent → `status: BLOCKED_ERROR`, record in `history`. Human resolves (returns to stage 04 with `iteration++` or manual correction).
8. **End-of-stage handoff:** follow the gate-inline protocol in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

## Outputs

- `output/verification-report.md` — technical report: declared-vs-delivered deliverables, CI status (lint/type/tests/coverage), **coverage audit** (% vs profile threshold), **sample-check test types** (3 tasks × declared vs delivered file), sample-check ADRs, verdict PASS/CONDITIONAL/FAIL.

## Sub_stage transitions

Valid enum: `05_in_progress`, `05_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/verification-report.md` exists.
- Global CI green (or CONDITIONAL verdict accepted by human).
- Sample-check ADRs completed (even with warnings).
- Human approved via gate (status `COMPLETED_AWAITING_HUMAN` → human responds).

## Canonical statuses available in this stage

- `IN_PROGRESS` — auditing deliverables and CI.
- `COMPLETED_AWAITING_HUMAN` — `verification-report.md` ready, human approves transition to 06.
- `BLOCKED_ERROR` — global CI red, declared deliverables absent in FS, serious inconsistency between plan.md and wave outputs, lead resolutions audit failed (`error_type: lead_resolution_audit_failed`, v3.9.0), OR e2e audit failed (`error_type: e2e_suite_missing|e2e_suite_stale|e2e_skip_unjustified`, v3.10.0).

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. **No stop points applicable in this stage** — verification is deterministic. CI failure = `BLOCKED_ERROR`, not a stop point. Late-detected architectural decisions roll to stage 06 (review) or to the next workspace via stage 08 output C.

## Skill superpowers reference

200tok summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/verification-before-completion-200tok.md`

Formal skill: `superpowers:verification-before-completion` (escape hatch).

## Gates

- **Human:** reviews `verification-report.md`, accepts PASS or CONDITIONAL, or requests return to stage 04 if FAIL.
- **Automatic (CI):** global CI runs + pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`.
- **Approval to transition:** human explicitly approves; sub_stage becomes `05_completed` in the next commit.

## End of stage handoff (gate inline + 1-stage-1-session)

Handoff is split into TWO phases within the SAME session. Human gate sits between them — `_kickoff.md` is only rendered AFTER approval. Bug v3.4.2 fixed: premature render+exit before approval created loop "kickoff → user approves in new session → kickoff again". Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

### Phase 1: WORK_DONE (after outputs are ready)

1. **Update L1** (`<workspace>/CONTEXT.md`):
   - `sub_stage = 05_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 05_in_progress`
   - `last_transition.to = 05_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "05_in_progress", to: "05_completed", commit_sha, note: "work done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; pre-commit hook validates atomicity):
   ```
   workspace <NNN>: stage 05 work done, awaiting gate
   ```
   Files: current stage outputs + L1. **DO NOT** include `_kickoff.md` (not rendered yet).

3. **Print gate prompt** for human. Do NOT exit the session. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 05 (verification) work COMPLETE — workspace <NNN-slug>

   Outputs ready for review:
     - <list of paths>

   L1: sub_stage=05_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review verification-report.md (PASS/CONDITIONAL/FAIL).
   Reply in chat:
     - "approved" / "ok proceed to 06" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition):
   - `stage_atual = 06`
   - `sub_stage = 06_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 05_completed`
   - `last_transition.to = 06_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "05_completed", to: "06_in_progress", commit_sha, note: "gate approved by human"}`

6. **Render `_kickoff.md`** in the next stage:
   - Path: `<workspace>/stages/06_review/_kickoff.md`
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render` or function `render_kickoff` from `{{SKILL_DIR}}/scripts/handoff.py`
   - L4-kickoff YAML frontmatter per schema in `references/session-handoff-protocol.md`
   - Body: prev_outputs + prev_decisions + pending for next stage

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 06
   ```
   Files: next stage `_kickoff.md` + updated L1.

8. **Print verbal KICKOFF block** for user (copy-paste for next session):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 05 (verification) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=06, sub_stage=06_in_progress, status=IN_PROGRESS
     - Kickoff: stages/06_review/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 06 (review).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/06_review/CONTEXT.md
     workspaces/<NNN-slug>/stages/06_review/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

9. **EXIT** the session. Do NOT continue to the next stage in the same session.

### Response "adjust X" (gate rejected)

If human replies with free text requesting an adjustment:
- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected", note: "human requested adjustment: X"}`. Sub_stage stays `05_completed` (returns to `05_in_progress` if change is non-trivial).
- Return to work as requested.
- When outputs are redone, return to Phase 1 (new commit 1/2 + new gate prompt).

### Response "abort"

If human replies "abort":
- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort", note: "human aborted at gate"}`.
- Commit + exit. Workspace stays in BLOCKED_ERROR awaiting manual intervention.

---

## v3.3.0 references applicable to this stage

- **Diagnose protocol fallback (`_references/runtime/diagnose-protocol.md`):**
  when CI fails OR coverage fails, activate 6-phase diagnose instead of trying
  ad-hoc fix. Phase 1 (build feedback loop) is THE skill — without a
  reproducible loop, do not advance. Hypotheses 3-5 ranked falsifiable. Tag debug
  logs with `[DEBUG-xxxx]` for cleanup grep at the end.
- **Additional output:** `output/diagnose-report.md` with repro evidence,
  ranked hypotheses, root cause, fix, regression test (path).
- **HITL loop (`_config/hitl-loop.template.sh`):** bash template for bugs
  that require human manual interaction. Customize `REPRO_STEPS`,
  `OBSERVE_CMD`, `PASS_PATTERN`.
