---
layer: L2
stage: "02"
stage_name: "design"
sub_stage_enum:
  - "02_in_progress"
  - "02_completed"
applicable_stop_points:
  - "stack"
  - "db"
  - "new_dep"
  - "paid_service"
  - "irreversible"
  - "over_eng"
  - "pii"
  - "adr_drift"
output_files:
  - "output/plan.md"
next_stage: "03"
---

# Stage 02 — design (L2)

Detailed technical design from the scope refined in discovery. Produces `plan.md` in the 4-block schema + Files touched + ADRs per task (consumed by the Wave Planner in 03). Creates new ADRs in `{{PROJECT_ROOT}}/.icm-main/docs/decisions/` (worktree linked to the base branch — model v3.4.0) when architectural decisions arise (stack, db, dependencies, paid services, irreversible migrations, etc.). Human gate before transitioning to 03.

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/output/discovery.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/output/recon-report.md | L4 | yes |
| 6 | {{PROJECT_ROOT}}/.icm-main/docs/decisions/ | L3 | conditional: read content of active ADRs listed in recon-report (filenames already indexed in 00). Read via worktree `.icm-main/`. |
| 7 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/profile-effective.yaml | L3 | yes |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/stop-points.md | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/4-block-contract-template.md | L3 | yes |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/writing-plans-200tok.md | L3 | yes |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/xp-conventions.md | L3 | yes |
| 12 | {{PROJECT_ROOT}}/.icm-main/docs/lessons.md | L3 | conditional: exists if inherited or accumulated. Read via worktree `.icm-main/`. |
| 13 | {{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md | L3 | conditional: exists if debt has been declared in prior iterations. Read via worktree `.icm-main/`. |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 15 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 16 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |
| 17 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/wave-planner-algorithm.md | L3 | conditional: referenced in discovery → technical tasks mapping |
| 18 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/design-system.md | L3 | conditional: effective profile has `design_system_required: True` (currently: `app_web_frontend`, `fullstack`) |
| 19 | {{PROJECT_ROOT}}/.icm-main/DESIGN.md | L3 | conditional: profile with `design_system_required: True` AND brownfield (file already exists). Read via worktree `.icm-main/`. |

## Não Lê (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/ and {{PROJECT_ROOT}}/.icm-main/tests/ — design is output-driven from discovery + ADRs; does not inspect existing code. If code context is critical, declare the dependency in plan.md (task with reading ADR) and revisit 01.
- ADRs not listed by recon-report — only reads those indexed in 00 or created in this session.
- Outputs of stages 03+ — they do not exist yet.
- {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/xp-conventions.md — read as Input #11; do NOT re-read from other sources.
- Sibling workspaces in {{PROJECT_ROOT}}/workspaces/<other>/ — scope is {{WORKSPACE}}.

## Process

1. **Pre-flight:** validate Input paths marked `yes`; sub_stage `02_in_progress`. If `discovery.md` is absent → status `BLOCKED_ERROR`.
2. **Read 4-block-contract-template** to internalize the mandatory schema for each task in plan.md (O QUE / COMO / NÃO QUERO / VALIDAÇÃO + Files touched + ADRs aplicáveis + Critical lessons + Tech debt paydown + Requires_peer_review).
   - **Canonical heading levels (CRITICAL):** task header is **h2** (`## Task <slug>: <title>`); 4-block subsections + metadata are **h3** (`### O QUE`, `### COMO`, `### NÃO QUERO`, `### VALIDAÇÃO`, `### Files touched`, `### Depends on`, etc). Wave-planner in stage 03 runs pre-flight `_detect_heading_drift` in `parse_plan` and aborts with `WavePlannerError` if it finds `#### Task` (h4) or `##### O QUE` (h5+). Do not copy the schema from the template with an offset; use literal `## ` and `### `.
3. **Map discovery → technical tasks:** break the macro option chosen in 01 into a list of discrete tasks. Each task fits into ≤1 wave of the Wave Planner (see `references/wave-planner-algorithm.md` — under construction, Wave 4 of the skill).
4. **For each task, write 4-block + metadata** (Files touched, ADRs aplicáveis, Critical lessons if there is a match, etc.). Direct language, avoids over-engineering.
5. **Detect stop points during design:** stack/db/new_dep/paid_service/irreversible/over_eng/pii/adr_drift. Calibration by tier in `_config/stop-points.md`. Trigger: pause, A/B/C menu, update L1 `BLOCKED_STOP_POINT`, wait for human response, resume.
6. **Spawn new ADRs** when an architectural decision is irreversible or diverges from what was declared: canonical v3.4.0 workflow via `.icm-main/` worktree:
   ```
   1. Write {{PROJECT_ROOT}}/.icm-main/docs/decisions/NNNN-<slug>.md
      (canonical format — see `_references/runtime/adr-format.md`)
   2. cd {{PROJECT_ROOT}}/.icm-main
   3. git add docs/decisions/NNNN-*.md
   4. git commit -m "docs(decisions): <slug> (workspace {{WORKSPACE}})"
   5. cd {{PROJECT_ROOT}}
   ```
   Numbering continuous from the highest NNNN in `.icm-main/docs/decisions/`. Validate 3-criteria gate first (`adr-format.md`).
7. **Detect adr_drift:** if design proposal diverges from an active ADR without a declared superseding → stop point `adr_drift`. Resolution: superseding ADR (`NNNN-supersedes-MMMM.md`) OR revision of the proposal to align.
7.5. **Design System (profiles `app_web_frontend` + `fullstack` only):** if the effective profile has `design_system_required: True` (read from `_config/profile-effective.yaml`):
   - **Brownfield:** read `{{PROJECT_ROOT}}/.icm-main/DESIGN.md` if it exists; design respects declared tokens.
   - **Greenfield (file absent):** present an A/B/C menu to the human:
     - **A) Create from scratch** — designer proposes initial tokens based on brand voice + audience captured in discovery.md.
     - **B) Inspire from example** — choose a reference brand from the [VoltAgent/awesome-design-md](https://github.com/VoltAgent/awesome-design-md) gallery (airbnb, apple, claude, figma, framer, ferrari, etc.).
     - **C) Extract from existing URL** — human provides URL and runs `npx designlang <url>` externally. Designer adapts the base output.
   - After choice, designer writes/updates `<project_root>/.icm-main/DESIGN.md` following the canonical Google Stitch schema (YAML frontmatter + section order: Overview → Colors → Typography → Layout → Elevation & Depth → Shapes → Components → Do's and Don'ts).
   - Commit to base branch via worktree:
     ```
     cd {{PROJECT_ROOT}}/.icm-main
     git add DESIGN.md
     git commit -m "design: {{WORKSPACE}} — design system v<N>"
     cd {{PROJECT_ROOT}}
     ```
   - Plan.md cites non-trivial components with a Component Spec table (Default/Hover/Active/Disabled) referencing declared tokens.
   - Tasks with frontend files get flag `requires_design_system: true` in metadata (consumed by lead in stage 04 — channel 2 inject).
   - Canonical doc: `_references/runtime/design-system.md`.
7.6. **Preview Loop — mock data schema + preview pages flag (v3.6.0):** if the effective profile has `preview_loop.preview_loop_enabled: true` (read from `_config/profile-effective.yaml`):
   - **Mock data strategy** read from effective (`preview_loop.mock_data_strategy`):
     - `fixtures` (experimental/tool): designer does NOT write a formal schema; plan.md only mentions expected `fixtures/*.json` paths.
     - `msw_faker` (development): designer describes in plan.md the `/api/*` endpoints expected by the frontend + payload shape (in pseudo-TS), sufficient for lead/subagent in stage 04 to write `mocks/handlers.ts` using MSW + Faker.
     - `msw_faker_zod` (production): designer writes a complete **Zod** schema in plan.md (code block), saved as `mocks/schema.ts` in stage 04. Schema is the source of truth for the API contract the real backend will implement later — refactoring mock → real = replacing MSW handler with a real HTTP call, without touching the component.
   - **Reusable components** get flag `requires_preview_page: true` in task metadata. Indicates to the subagent in stage 04 that along with the component it should write `preview/<component>/page.tsx` (Next.js app router) or equivalent for the detected build tool, with ≥4 states (Default/Hover/Active/Disabled). Canonical path in `preview_loop.preview_pages_path` (default `preview/`).
   - **Routes map (CDP fallback):** designer populates `output/routes.md` listing planned routes + main component per route + associated fixture/handler. Activates automatic fallback when CDP is unavailable in stage 04.
   - **Optional ASCII wireframe:** plan.md task with non-trivial layout (e.g., multi-grid dashboard) includes an ASCII wireframe in the `COMO` block. Stage 04 lead injects the wireframe in the subagent's channel 2. Wireframe does NOT replace DESIGN.md tokens; it is aux for layout coords.
   - Canonical doc: `_references/runtime/preview-loop-protocol.md`.
8. **Define global Test Strategy for the workspace** (once in plan.md, not per task). Read `test_specs` from `_config/profile-effective.yaml` for calibration. Mandatory section with:
   - **Framework**: language → main framework (e.g., Python → pytest + httpx; TS → vitest + @testing-library/react)
   - **Test pyramid**: unit/integration/e2e proportion justified by profile
   - **Coverage threshold**: from `test_specs.coverage_threshold` of the effective profile (minimum 80% development, 90% production in lines/branches)
   - **Critical path 100%**: authentication, payment, PII code must have mandatory 100% unit coverage
   - **Test file location**: convention for where test files live (co-located vs `tests/`)
   - If profile == `agent_ia`: include **Eval Strategy** (golden_output, eval_threshold, determinism seed)
   - If profile == `ml_project`: include **Model Regression** (dataset fixtures, performance baseline)
9. **Write `output/plan.md`** with sections: Overview (5-10 lines); **Test Strategy** (section 8 above); Tasks (list, each with 4-block + metadata); ADRs created in this session; Triggered stop points (if any); Inherited tech debt (if any); Acceptance metrics (linked to discovery.md).
10. **End-of-stage handoff:** follow the gate-inline protocol in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

## Outputs

- `output/plan.md` — technical design with **global Test Strategy** + list of tasks in the 4-block schema (each task with ≥1 test file in `Files touched`), consumed by the Wave Planner in 03. ADRs live in `{{PROJECT_ROOT}}/.icm-main/docs/decisions/` (base branch worktree) — plan.md cites created filenames as path relative to `.icm-main/`.

## Sub_stage transitions

Valid enum: `02_in_progress`, `02_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/plan.md` exists with at least 1 task in the 4-block schema + complete metadata.
- `output/plan.md` contains a **Test Strategy** section filled with framework, pyramid, coverage threshold, and test file location.
- Every task with functional code has ≥1 test file in `Files touched`.
- Stop points triggered during the session are resolved (status returns to `IN_PROGRESS` before completing).
- New ADRs committed to base branch via `{{PROJECT_ROOT}}/.icm-main/docs/decisions/` (if there was an architectural decision).
- Human approved via gate (status `COMPLETED_AWAITING_HUMAN` → human replies "approved, proceed to 03").

## Canonical statuses available in this stage

- `IN_PROGRESS` — active design, writing plan.md and ADRs.
- `COMPLETED_AWAITING_HUMAN` — plan.md ready, human reviews/edits before transitioning.
- `BLOCKED_STOP_POINT` — A/B/C menu awaiting response (any of the 8 applicable IDs).
- `BLOCKED_ERROR` — discovery.md absent, malformed superseding ADR, or hook rejected commit.

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. IDs triggerable in stage 02 design:

- `stack` — proposal changes language/framework/runtime vs active ADR. Always `hard`.
- `db` — new engine or schema design. Always `hard`.
- `new_dep` — new npm/pip/cargo dependency in the manifest (license/maintenance/size). Always `hard`.
- `paid_service` — recurring SaaS (calibrated by tier: warning R$50 / hard R$200/500/1000).
- `irreversible` — drop table, destructive migration, no-rollback schema. Always `hard`.
- `over_eng` — 3+ new abstraction layers without requirement (warning experimental/tool, hard development/production).
- `pii` — LGPD, sensitive data (warning experimental, hard tool/development, hard+DPO production).
- `adr_drift` — proposal diverges from existing ADR without declared superseding. Always `hard`.

Trigger: agent pauses, writes A/B/C menu in the output, updates L1 `status: BLOCKED_STOP_POINT`. Human responds, session resumes with `IN_PROGRESS`. Resolved architectural decisions become ADRs in `{{PROJECT_ROOT}}/.icm-main/docs/decisions/`.

## Skill superpowers reference

200tok summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/writing-plans-200tok.md`

Formal skill: `superpowers:writing-plans` (escape hatch — actual invocation only if design demands structured deep planning beyond the summary).

## Gates

- **Human:** reviews `output/plan.md` and created ADRs; approves or requests adjustments. Can edit plan.md directly if they disagree.
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`. ADRs commit via `cd {{PROJECT_ROOT}}/.icm-main && git commit ...` — those commits land in base_branch automatically (linked worktree).
- **Approval to transition:** human explicitly approves; sub_stage becomes `02_completed` in the commit that records the approval. Pending stop points block the transition.

## End of stage handoff (gate inline + 1-stage-1-session)

Handoff is split into TWO phases within the SAME session. Human gate sits between them — `_kickoff.md` is only rendered AFTER approval. Bug v3.4.2 fixed: premature render+exit before approval created loop "kickoff → user approves in new session → kickoff again". Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

### Phase 1: WORK_DONE (after outputs are ready)

1. **Update L1** (`<workspace>/CONTEXT.md`):
   - `sub_stage = 02_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 02_in_progress`
   - `last_transition.to = 02_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "02_in_progress", to: "02_completed", commit_sha, note: "work done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; pre-commit hook validates atomicity):
   ```
   workspace <NNN>: stage 02 work done, awaiting gate
   ```
   Files: current stage outputs + L1. **DO NOT** include `_kickoff.md` (not rendered yet).

3. **Print gate prompt** for human. Do NOT exit the session. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 02 (design) work COMPLETE — workspace <NNN-slug>

   Outputs ready for review:
     - <list of paths>

   L1: sub_stage=02_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review the outputs above.
   Reply in chat:
     - "approved" / "ok proceed to 03" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition):
   - `stage_atual = 03`
   - `sub_stage = 03_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 02_completed`
   - `last_transition.to = 03_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "02_completed", to: "03_in_progress", commit_sha, note: "gate approved by human"}`

6. **Render `_kickoff.md`** in the next stage:
   - Path: `<workspace>/stages/03_wave_planner/_kickoff.md`
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render` or function `render_kickoff` from `{{SKILL_DIR}}/scripts/handoff.py`
   - L4-kickoff YAML frontmatter per schema in `references/session-handoff-protocol.md`
   - Body: prev_outputs + prev_decisions + pending for next stage

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 03
   ```
   Files: next stage `_kickoff.md` + updated L1.

8. **Print verbal KICKOFF block** for user (copy-paste for next session):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 02 (design) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=03, sub_stage=03_in_progress, status=IN_PROGRESS
     - Kickoff: stages/03_wave_planner/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 03 (wave_planner).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/03_wave_planner/CONTEXT.md
     workspaces/<NNN-slug>/stages/03_wave_planner/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

9. **EXIT** the session. Do NOT continue to the next stage in the same session.

### Response "adjust X" (gate rejected)

If human replies with free text requesting an adjustment:
- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected", note: "human requested adjustment: X"}`. Sub_stage stays `02_completed` (returns to `02_in_progress` if change is non-trivial).
- Return to work as requested.
- When outputs are redone, return to Phase 1 (new commit 1/2 + new gate prompt).

### Response "abort"

If human replies "abort":
- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort", note: "human aborted at gate"}`.
- Commit + exit. Workspace stays in BLOCKED_ERROR awaiting manual intervention.

---

## v3.3.0 references applicable to this stage

- **ADR 3-criteria gate (`_references/runtime/adr-format.md`):** before
  spawning an ADR, validate ALL 3 criteria: (1) hard to reverse, (2)
  surprising without context, (3) result of real trade-off. Fail on any
  → goes to `decisions.md` as a note, NOT an ADR.
- **OUT-OF-SCOPE check (`_references/runtime/out-of-scope-kb.md`):** if
  `iteration > 0` in L1, read `<workspace>/_out-of-scope/*.md` before
  proposing design. Match with prior rejection → surface to human before
  re-proposing.
- **HITL/AFK in plan.md (`_references/runtime/task-types-hitl-afk.md`):**
  each task in plan.md gets field `**Type:** HITL|AFK`. AFK is the default.
  HITL requires justification in field `**Reason:**`.
- **AGENT-BRIEF compatibility (`_references/runtime/agent-brief-template.md`):**
  4-block (O QUE / COMO / NÃO QUERO / VALIDAÇÃO) per task MUST be parseable
  by `agent-brief-render.py` in stage 04. Mapping: O QUE→Summary+Desired,
  COMO→Key interfaces (no absolute paths!), NÃO QUERO→Out of scope,
  VALIDAÇÃO→Acceptance criteria.
- **Design It Twice (`_references/runtime/design-it-twice.md`):** modules
  marked `core: true` in plan.md trigger Design It Twice. Spawn 3+
  parallel Agent tool calls with distinct constraints (minimize
  interface / maximize flexibility / optimize common caller). Output in
  `output/design-alternatives-<module>.md` + final decision in decisions.md.
- **Deep modules (`_references/runtime/deep-modules.md`, v3.4.1):** for
  each new module introduced by the design, validate checklist of 5 items:
  minimal interface (≤5 methods), information hiding (API does not expose state),
  single responsibility (name without and/or), deletion test (blast radius
  <30% callers need to adapt logic), alternative considered in ADR.
  ≥2 items failing = back to the drawing board. Skip for pure bug fix or trivial
  single-function module.

## Ubiquitous Language

Inputs: `_config/CONTEXT.md` (L3, populated in stage 01) is mandatory.
Glossary vocabulary must be used consistently in plan.md, ADRs,
and output/. Auto-QA Akita validates consistency.

## v3.4.0 — Parallel worktree

Stage pre-flight includes validating the `.icm-main/` worktree exists in
`{{PROJECT_ROOT}}/`. Absent = `BLOCKED_ERROR`; recovery wizard suggests
`git worktree add .icm-main {{BASE_BRANCH}}`. Canonical doc:
`_references/runtime/worktree-model.md`.
