---
layer: L2
stage: "07"
stage_name: "merge"
sub_stage_enum:
  - "07_in_progress"
  - "07_completed"
applicable_stop_points:
  - "irreversible"
  - "prod_migration"
output_files:
  - "output/merge-report.md"
next_stage: "08"
---

# Stage 07 — merge (L2)

Finalizes the implementation cycle: integrates the `workspace_branch` rebased into `base_branch` (usually `main`), optionally opens a PR or creates a release tag. Decision "direct merge / PR / tag-only" is a human menu. After execution, the workspace automatically transitions to **stage 08 (feedback intake)** with `status: COMPLETED_AWAITING_HUMAN` — workspace stays "alive" waiting for the human to return with feedback after real use of the project. Workspace ONLY closes (status `COMPLETED`) when stage 08 decides output A (close).

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/07_merge/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/06_review/output/review-report.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/.git/config | L3 | yes (read-only — which remote, which base_branch) |
| 6 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/finishing-a-development-branch-200tok.md | L3 | yes |
| 7 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/stop-points.md | L3 | yes |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/07_merge/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/, {{PROJECT_ROOT}}/.icm-main/tests/ — merge does not inspect code (review and verification already validated it).
- Outputs of stages 00–05 — review-report already consolidates what matters for the merge decision.
- {{PROJECT_ROOT}}/.icm-main/docs/decisions/ in full — ADRs were already applied in stages 02/04/06.
- Sibling workspaces.

## Process

1. **Pre-flight:** validate Input paths; sub_stage `07_in_progress`. review-report.md ABSENT or indicating P0/P1 → `BLOCKED_ERROR` (should not be in 07 in that case).
2. **Verify git state:** `workspace_branch` exists, is rebased onto `base_branch`, working tree clean. If not — `BLOCKED_ERROR` with specific message.
3. **Detect stop points:**
   - Irreversible operations in the merge (force-push, drop) → `irreversible` (always `hard`).
   - Schema migration with production data → `prod_migration` (always `hard`).
4. **Human A/B/C menu** (written in chat, not in a file):
   - **A) Direct merge** into `base_branch` (`git merge --no-ff` or `--squash`, per project convention declared in xp-conventions or git config).
   - **B) Open PR** via `gh pr create` (or equivalent), awaits external human review before final merge.
   - **C) Tag-only** — creates release tag without automated merge (used for deliveries that go through an external deploy gate).
5. **Execute the human's choice:**
   - A: final rebase + merge + push into `base_branch`.
   - B: push the branch + `gh pr create` with link to review-report.
   - C: `git tag -a v<X>.<Y>.<Z>` + push tag.
6. **Write `output/merge-report.md`:** decision taken (A/B/C), commands executed, resulting commit_sha (merge commit, PR URL, or tag), post-merge CI status if applicable.
7. **End-of-stage handoff:** follow the gate-inline protocol in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate over merge-report → Phase 2 GATE_APPROVED with immediate auto-transition 07→08). Stage 07 is special: after gate approved, workspace immediately transitions to stage 08 with `status: COMPLETED_AWAITING_HUMAN` (different semantics: workspace stays alive waiting for real-world feedback). Workspace only closes (`COMPLETED`) in stage 08 output A.

## Outputs

- `output/merge-report.md` — merge report: decision A/B/C, executed commands, resulting commit_sha (merge commit / PR URL / tag), post-merge CI state.

## Sub_stage transitions

Valid enum: `07_in_progress`, `07_completed`.

IN_PROGRESS → 07_completed transition fires when:
- `output/merge-report.md` exists.
- Human decision A/B/C executed successfully (commit_sha recorded in merge-report).
- Human confirmed via gate.

Immediately after `07_completed`, session TRANSITIONS to stage 08 (`stage_atual: "08"`, `sub_stage: "08_in_progress"`, `status: COMPLETED_AWAITING_HUMAN`). Workspace stays alive waiting for human feedback after real use. Workspace only closes (`status: COMPLETED`) when stage 08 output A (close) is decided.

`next_stage: "08"` — stage 07 transitions automatically to 08 (feedback intake).

## Canonical statuses available in this stage

- `IN_PROGRESS` — preparing merge, waiting for human A/B/C choice.
- `COMPLETED_AWAITING_HUMAN` — merge done, session transitioned to stage 08; workspace waiting for human feedback after real use.
- `BLOCKED_STOP_POINT` — `irreversible` or `prod_migration` triggered; A/B/C menu awaiting response.
- `BLOCKED_ERROR` — review-report indicated P0/P1, working tree dirty, rebase failed, or push rejected.

`COMPLETED` is NOT set in this stage — definitive close only happens in stage 08 output A (close).

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. IDs triggerable in stage 07 merge:

- `irreversible` — destructive operation (force-push on a shared branch, drop in prod, credential rotation without grace-window). Always `hard`.
- `prod_migration` — schema migration with production data (blocking DDL, type change invalidating existing rows). Always `hard`.

Trigger: agent pauses, writes A/B/C menu in the output, updates L1 `status: BLOCKED_STOP_POINT`. Human responds, session resumes with `IN_PROGRESS`.

## Skill superpowers reference

200tok summary (mandatory consultation):

- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/finishing-a-development-branch-200tok.md`

Formal skill (escape hatch): `superpowers:finishing-a-development-branch`.

## Gates

- **Human:** chooses A/B/C in the merge menu; confirms the merge-report at the end.
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`. Post-merge, CI of `base_branch` validates the integrated state.
- **Approval to transition:** human confirms merge-report; sub_stage becomes `07_completed` and status immediately transitions to `COMPLETED_AWAITING_HUMAN` (stage 08). `COMPLETED` is NOT set in this stage — definitive close only in stage 08 output A.

## End of stage handoff (gate inline + auto-transition 07→08)

Stage 07 has gate-inline + auto-transition to 08 (no second gate). Bug v3.4.2 fixed: premature render+exit before merge-report approval created loop. Stage 08 does NOT have its own output gate — `COMPLETED_AWAITING_HUMAN` in 08 means "waiting for real-world feedback", not "waiting for output approval". Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

### Phase 1: WORK_DONE (after merge executed + merge-report.md written)

1. **Update L1** (`<workspace>/CONTEXT.md`):
   - `sub_stage = 07_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 07_in_progress`
   - `last_transition.to = 07_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{event: "stage_transition", from: "07_in_progress", to: "07_completed", commit_sha, note: "merge done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; **DO NOT** include `_kickoff.md`):
   ```
   workspace <NNN>: stage 07 merge done, awaiting gate
   ```
   Files: `output/merge-report.md` + L1.

3. **Print gate prompt** for human. Do NOT exit. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 07 (merge) work COMPLETE — workspace <NNN-slug>
   Decision A/B/C: <decision executed>. commit_sha/PR/tag: <ref>.

   Outputs ready for review:
     - stages/07_merge/output/merge-report.md

   L1: sub_stage=07_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: confirm merge-report.md.
   Reply in chat:
     - "approved" / "ok transition to 08" → I render kickoff for 08 and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

### Phase 2: GATE_APPROVED (after human confirms) — auto-transition 07→08

Stage 07 is unique: after gate approved, workspace IMMEDIATELY TRANSITIONS to stage 08 with status `COMPLETED_AWAITING_HUMAN` (different semantics: workspace stays alive waiting for real-world feedback, not output review). No second gate.

5. **Update L1** (second transition — auto-transit 07→08):
   - `stage_atual = 08`
   - `sub_stage = 08_in_progress`
   - `status = COMPLETED_AWAITING_HUMAN` (active workspace waiting for human feedback after real use)
   - `last_transition.from = 07_completed`
   - `last_transition.to = 08_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{event: "stage_transition", from: "07_completed", to: "08_in_progress", commit_sha, note: "gate approved, auto-transit 07→08 (workspace alive awaiting real-world feedback)"}`

6. **Render `_kickoff.md`** in `<workspace>/stages/08_feedback_intake/_kickoff.md` via `python {{SKILL_DIR}}/scripts/handoff.py render`. Fields:
   - `prev_outputs`: `output/merge-report.md` (path + summary "merge done A/B/C, commit_sha=X")
   - `prev_decisions_summary`: short line with A/B/C decision + resulting commit/tag/PR
   - `pending_for_this_stage`: ["wait for human feedback after real use of the project", "infer intent for A/B/C"]

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, auto-transit 07→08 (awaiting feedback)
   ```
   Files: L1 + `stages/08_feedback_intake/_kickoff.md`.

8. **Print verbal KICKOFF block** for user. Canonical text (no A/B/C menu — session 08 will infer from the feedback intent):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 07 (merge) GATE APPROVED — workspace <NNN-slug>

   Workspace transitioned to stage 08 (feedback intake) with status
   COMPLETED_AWAITING_HUMAN. Workspace stays alive until you return
   with feedback after real use of the project.

   Workspace updated at commit <sha>:
     - L1: stage_atual=08, sub_stage=08_in_progress, status=COMPLETED_AWAITING_HUMAN
     - Outputs: stages/07_merge/output/merge-report.md
     - Kickoff: stages/08_feedback_intake/_kickoff.md generated

   🔄 KICKOFF next session (AFTER real use, no deadline):
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 08 (feedback_intake).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/08_feedback_intake/CONTEXT.md
     workspaces/<NNN-slug>/stages/08_feedback_intake/_kickoff.md

   Paste free-form feedback — session 08 reads outputs, infers intent
   (bug fix → restart stage X, new feature → spawn workspace,
   all OK → close), confirms with you before executing.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

9. **EXIT** the session.

### Response "adjust X" (gate rejected)

If human replies with free text requesting adjustment in the merge-report (re-run merge with a different decision, redo push, etc.):
- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected", note: "human requested adjustment in merge: X"}`. Sub_stage stays `07_completed`.
- Return to work as requested. May involve re-execution of Process step 5 (execute new A/B/C choice).
- When outputs are redone, return to Phase 1.

### Response "abort"

- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort"}`. Commit + exit.
