---
layer: L2
stage: "08"
stage_name: "feedback_intake"
sub_stage_enum:
  - "08_in_progress"
  - "08_decided_A"
  - "08_decided_B"
  - "08_decided_C"
applicable_stop_points:
  - "runtime_cleanup_failed"  # v3.7.0 — strict universal, all tiers
output_files:
  - "output/intake-report.md"
next_stage: null
---

# Stage 08 — feedback_intake (L2)

Universal iteration gate of the ICM cycle. Workspace transitions here automatically after stage 07 and stays in `COMPLETED_AWAITING_HUMAN` waiting for the human to return with free-form feedback after real use of the project (weeks/months with no deadline). When the human opens a new session and pastes free-form feedback (loose text, no menu), the session **infers intent** and maps it to one of 3 outputs: A) close workspace + lessons in `docs/lessons.md`, B) restart stage X (X ∈ 01..07) with `iteration++`, C) spawn new workspace via human pasting command in a new session. Session confirms the inference with the human before executing (mini-menu y/n/adjust). Collects logs (if `logs_root` is declared), extracts 4 blocks from the free-form feedback, calculates top-N error patterns. Does NOT write new code — only analyzes, infers, and transitions state. Literal protocol in `_references/runtime/feedback-intake-stage08.md`.

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/08_feedback_intake/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/output/ | L4 | conditional: exists if discovery ran (profile did not skip 01) |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/ | L4 | conditional: exists if design ran |
| 6 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/ | L4 | conditional: exists if wave planner ran |
| 7 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/04_implementation_waves/output/ | L4 | conditional: exists if implementation ran |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/05_verification/output/ | L4 | conditional: exists if verification ran |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/06_review/output/ | L4 | conditional: exists if review ran |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/07_merge/output/ | L4 | yes (pre-condition sample-check) |
| 11 | {{PROJECT_ROOT}}/.icm-main/docs/lessons.md | L3 | conditional: append only in output A |
| 12 | {{LOGS_ROOT}} | L3 | conditional: optional — sample of last 30 days if L0 declares `logs_root` ≠ null |
| 13 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/feedback-intake-stage08.md | L3 | yes (literal protocol — local copy of the reference) |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/08_feedback_intake/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. In stage 08 normally ABSENT — human triggers manually after real use, there is no prior automatic session. |
| 15 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff (output B generates kickoff) |
| 16 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/recovery-wizard.md | L3 | conditional: referenced in pre-flight if workspace is inconsistent |

**Note on `{{LOGS_ROOT}}`:** placeholder resolved by bootstrap from the `logs_root` field of L0. If `logs_root: null` (greenfield, text, skill), bootstrap substitutes with an inert marker and the input is skipped in pre-flight. If `logs_root` is a real path, session samples the last 30 days.

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/, {{PROJECT_ROOT}}/.icm-main/tests/ — stage 08 does not revisit code.
- Other workspaces in {{PROJECT_ROOT}}/workspaces/<other>/ — output C (spawn) consults the old workspace's CONTEXT.md via `spawn_from`, but that is the responsibility of the NEW workspace; the current workspace does not read others.
- {{PROJECT_ROOT}}/.icm-main/docs/decisions/ — ADRs are not edited in stage 08; inheritance in output C is the new workspace's responsibility.

**v3.7.0:** `{{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md` MAY be **written** (append) in outputs A/B if free-form feedback reveals durable technical debt (not a lesson). Difference lessons vs tech_debt: lesson = learning for next workspace; technical debt = trackable item that needs to be addressed in future code. Both coexist in output A; B appends only if feedback explicitly cites debt.

## Runtime Cleanup Checklist (v3.7.0 — mandatory pre-Process)

BEFORE any Process step, execute the runtime cleanup checklist. Strict universal — all tiers (`experimental` → `production`) go through the checklist without opt-out.

**Command:**

```bash
python {{SKILL_DIR}}/scripts/runtime-status.py \
    --workspace-root {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}} \
    --project-root {{PROJECT_ROOT}} \
    --format text
```

**6 categories verified:**

| # | Category | Detects |
|---|---|---|
| 1 | `dev_servers` | Entries kind=dev_server alive in runtime-registry |
| 2 | `background_tasks` | Entries kind=background_task alive |
| 3 | `docker` | Containers with label `icm-workspace={{WORKSPACE}}` |
| 4 | `wave_branches` | Orphan git branches `wave-<workspace_num>-*` |
| 5 | `working_tree` | `git status --short` at project_root (workspace branch) |
| 6 | `untracked` | `.icm-main/` dirty (base worktree) |

**Behavior per non-clean detected category:**

```
✗ dev_servers: 1 dev server(s) alive: pid=12345

[s] resolved (dev server killed / unregistered), resume checklist
[n] cancel stage 08 (status returns to COMPLETED_AWAITING_HUMAN)
[edit] describe adjustment
```

**flow:**

1. Session runs full checklist (all 6 categories).
2. For each non-clean category, session prints human confirm (per category, not 1 global confirm — strict universal).
3. Human resolves (kill process, delete branch, etc.) and replies `[s]` to resume checklist.
4. Re-run checklist until **all categories clean**.
5. Persistent failure / human cancellation → stop point #13 `runtime_cleanup_failed`. Status `BLOCKED_STOP_POINT`.
6. Success → proceed to Process step 1.

**Output reported in `output/intake-report.md`:** section §"Runtime cleanup pre-output (v3.7+)" with final checklist snapshot + resolved categories + warnings (if any cleanup was skipped via explicit human menu C).

Canonical doc: `_references/runtime/runtime-cleanup-protocol.md`.

## Process

1. **Pre-flight — mandatory pre-condition:** L1 must declare `stage_atual: "08"` with `sub_stage: 08_in_progress` (automatic transition from stage 07) and `status: COMPLETED_AWAITING_HUMAN`. If status ∈ {`IN_PROGRESS`, `BLOCKED_*`} → inconsistent workspace (recovery wizard). If `stage_atual ≠ 08` → refuse with "workspace has not yet reached 08 (finish 07 first)". If status undefined → stop point 11 `workspace_corrupt`.

   **Step 0 (v3.7.0 — strict universal):** run Runtime Cleanup Checklist (§above) BEFORE step 1. Blocks transition if any category is non-clean and human has not confirmed cleanup. Status may trigger stop point #13 `runtime_cleanup_failed` if human cancels.
2. **Set `status: IN_PROGRESS`** in L1 (exits `COMPLETED_AWAITING_HUMAN` while session works). Append `history` event `feedback_session_started`.
3. **Log collection** (only if `logs_root` ≠ null in L0): sample last 30 days of `{{LOGS_ROOT}}`. If path inaccessible/empty, note "logs empty/inaccessible" and continue.
4. **Receive free-form feedback from human:** human pastes feedback as loose text (not menu, not 4 guided blocks). Session validates ≥1 substantive sentence. During prolonged silence / explicit empty message like "everything OK, close" → consider intent A close.
5. **Intent inference (session decides A/B/C autonomously):** apply heuristics below. If multiple categories match, priority: B > C > A (point correction beats pivot; pivot beats close). If ambiguous, session asks short clarification before proceeding.

   | Signal in free-form feedback | Inferred output | Detail |
   |---|---|---|
   | "bug in X", "breaks", "error", "doesn't work", "regression", "fail", "crashed" | **B** restart | Map stage of bug: tests/CI → 05, code → 04, bad design → 02, wrong requirements → 01, review missed → 06, merge → 07 |
   | "all OK", "working", "close", "end project", "done", "no feedback", silence | **A** close | Workspace archived + lessons |
   | "new project", "pivot", "change direction", "big new feature", "other workspace", "start from scratch with X learned" | **C** spawn | Workspace closes + spawn instruction |
   | "small extension", "iterate more", "return to stage Y", explicit mention of stage by number/name | **B** with explicit X | Stage extracted from mention |
   | Mix "bug + new feature" | prefer **B** first (fix bug); user can trigger 08 again for C | |

6. **Mini-confirm with human** (1 single menu, no raw A/B/C):
   ```
   Understood: <inferred output in prose>
   Ex: "restart stage 02 design to revise API contract"
   Ex: "spawn new workspace for billing feature"
   Ex: "close workspace, all OK"

   [s] confirm   [n] cancel and ask again   [edit] describe what to adjust
   ```
7. **Top-N error patterns analysis:** group logs + feedback into ≤5 patterns with `frequency`, `impact` (low/medium/high/critical), and `evidence`. Accepts 0-2 patterns if logs are empty and feedback is short.
8. **Extract 4 blocks from free-form feedback** (parsing for audit, not an inline question): WHAT WORKED / WHAT DIDN'T WORK / WHAT PAIN PERSISTS / WHAT LESSON TO TAKE. Accepts empty blocks (does not force filling).
9. **Write `output/intake-report.md`** with fixed sections: Logs sample, Free-form feedback (literal), 4 extracted blocks, Top-N patterns (table), Inference (output + triggered heuristic + confidence), Final decision (after mini-confirm).
10. **Execute confirmed output** per sections "Output A/B/C" below.
11. **Atomic commit** (pre-commit hook validates L1 ↔ outputs ↔ lessons atomicity; prefix `intake:` or `feedback:`).

## Outputs

- `output/intake-report.md` — intake report: logs sample (or n/a), free-form feedback (literal), 4 extracted blocks, top-N error patterns (table), inference (triggered heuristic + confidence), final decision post human-confirm.

## Sub_stage transitions

Valid enum: `08_in_progress`, `08_decided_A`, `08_decided_B`, `08_decided_C`.

Transitions:
- `08_in_progress → 08_decided_A`: human chooses A. `status: COMPLETED`. Lessons appended to `docs/lessons.md`.
- `08_in_progress → <XX>_in_progress` (output B): human chooses B with X ∈ 01..07. `iteration++`. `status: IN_PROGRESS`. Old outputs moved to `output-iteration-<N>/`. Note: the sub_stage transitions DIRECTLY to the stage X — there is no stable persistent `08_decided_B`; it appears only as an event in `history`. (Spec requires the enum `08_decided_B` for compatibility; sessions transition through it and then move to `<XX>_in_progress`.)
- `08_in_progress → 08_decided_C`: human chooses C. `status: COMPLETED`. `spawn_to` set. Bootstrap of the new workspace is the human's responsibility in a separate session.

`next_stage: null` — stage 08 has no deterministic next stage. Outputs A and C end the workspace; output B returns to stage X via `last_transition`/`history`, not via `next_stage`.

**Output B validation:** session refuses X ∉ {`01`, `02`, `03`, `04`, `05`, `06`, `07`}. To change `project_root` or project type, use output C.

**Output C UX:** session does NOT bootstrap new workspace. Only prints explicit command for human to paste in a new session. Preserves separation "skill is a one-shot midwife, exits".

## Canonical statuses available in this stage

- `IN_PROGRESS` — collecting logs/feedback, writing intake-report, or awaiting human A/B/C choice. Also the final status in output B (at the return stage X).
- `COMPLETED` — output A (workspace closed, lessons appended) or output C (workspace closed with `spawn_to` set).
- `BLOCKED_ERROR` — `workspace_corrupt` detected in pre-flight, `intake-report.md` cannot be written (disk full, permission), pre-commit hook rejects, or human interrupts before deciding A/B/C (status stays `IN_PROGRESS` in `08_in_progress`; next session resumes).

## Applicable stop points

`applicable_stop_points: []` — stage 08 does NOT trigger stop points by design. It is analysis + inference + direct A/B/C decision; there is no architectural trade-off to escalate. Stops detected during use of the workspace output roll to the next workspace via output C (or to the restart via output B).

The only exception is stop point 11 `workspace_corrupt`, which may appear in pre-flight if the workspace state is inconsistent — but that is treated as a pre-condition error, not a regular stage stop point.

## Intent inference (canonical heuristics)

Detailed mapping free-form feedback → output A/B/C. Priority order when multiple matches: **B > C > A**.

### Output B (restart stage X) — signals

- Keywords: "bug", "breaks", "error", "fail", "regression", "crashed", "doesn't work", "wrong", "missed", "slipped through"
- Phrases: "need to fix X", "return to Y", "redo Z"
- Explicit mention of stage by number (`stage 02`, `stage 4`) or name (`design`, `review`, `verification`, etc.)

**Bug → stage X mapping:**

| Bug type | X inferred |
|---|---|
| Test / CI failure / automated regression | 05 verification |
| Runtime bug / broken code / wrong logic | 04 implementation_waves |
| Code smell, bad design that passed review, 7-fold dimension missed | 06 review |
| Wrong plan / inadequate architecture / wrong ADR | 02 design |
| Wrong wave plan / bad DAG / poorly mapped dependencies | 03 wave_planner |
| Missing requirements / shallow discovery / missed question | 01 discovery |
| Merge with problem / push to wrong branch / wrong tag | 07 merge |
| Incomplete recon (rare — usually prefers C) | Does NOT allow restart of 00; if intent is to change type/project_root, becomes C |

### Output C (spawn new workspace) — signals

- Keywords: "pivot", "change direction", "new project", "other workspace", "big new feature", "start from scratch", "this learning goes to another"
- Phrases: "this project served for X but now I need different Y", "evolution beyond scope"
- Change of profile/tier/project_root → always C

### Output A (close) — signals

- Keywords: "all OK", "working", "close", "end", "done", "no feedback", "nothing to report"
- Human silence after a direct question
- Short neutral message like "ok"

### Confidence score

Session computes `confidence` (0.0-1.0) based on:
- Number of signals matched (more signals → higher confidence)
- Specificity (`stage 02` > `has bug`)
- Unambiguity (no mixture of categories)

If `confidence < 0.6`, session asks short clarification. If `≥ 0.6`, proceeds to mini-confirm.

### Mini-confirm template

```
Understood: <inferred output in prose, 1-2 sentences>

Examples:
  - "Restart stage 02 design to revise API contract (bug in endpoints)"
  - "Spawn new workspace for billing feature (scope outside current)"
  - "Close workspace — all OK, lessons recorded"

[s] confirm and execute
[n] cancel, ask again
[edit] describe the adjustment (ex: "actually restart stage 03, not 02")
```

## Skill superpowers reference

No direct skill superpowers for stage 08. The literal protocol is at:

- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/feedback-intake-stage08.md`

This is the local copy (in the workspace) of the canonical reference `references/feedback-intake-stage08.md` of the skill. Wave 4 of the rewrite copies the reference to `_references/runtime/`.

## Gates

- **Human:** triggers stage 08 manually (never automatic). Provides the 4 feedback blocks inline. Chooses A/B/C in the menu (may disagree with the recommendation).
- **Automatic (CI):** pre-commit hook validates L1 ↔ outputs ↔ `docs/lessons.md` atomicity (in output A). Pre-commit validates that `output-iteration-<N>/` (output B) is only created in commits with prefix `intake:` or `feedback:`.
- **Approval to transition:** human explicitly states A/B/C choice; sub_stage transitions per choice in the commit that records the decision. Outputs A and C take `status: COMPLETED`; output B takes stage X with `status: IN_PROGRESS` and `iteration: N+1`.

## End of stage handoff (1-stage-1-session)

**Stage 08 outputs (Q12 of the plan):**

- **A — Close:** workspace `COMPLETED`. Session exits WITHOUT generating kickoff.
- **B — Restart stage X:** L1 `iteration++`, `stage_atual=X`, `sub_stage=X_in_progress`. GENERATE kickoff in `stages/<X>_<name>/_kickoff.md` inheriting prior outputs in `prev_outputs` + history append. Print verbal KICKOFF for next session.
- **C — Spawn new workspace:** does NOT generate kickoff (new workspace is another one). Prints instruction for user to invoke `/xp-icm-workflow` new (new skill bootstraps inheriting lessons+ADRs from parent via `--spawn-from <NNN>`).

Detail per output:

### Exit A — Close

1. **Update L1**:
   - `sub_stage = 08_decided_A`
   - `status = COMPLETED`
   - `last_transition.from = 08_in_progress`
   - `last_transition.to = 08_decided_A`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from, to, commit_sha, note: "output A close"}`
2. Append new lessons (from "WHAT LESSON TO TAKE") to `{{PROJECT_ROOT}}/.icm-main/docs/lessons.md` respecting strict frontmatter.
3. **(v3.7.0) Append tech debt during intake — conditional, mandatory when debt is cited:**

   Use this decision tree to distinguish lesson from tech debt:

   - Is there a concrete file, module, or class to refactor? → **tech_debt.md** (trackable item)
   - Is it a general practice or pattern to adopt/avoid? → **lessons.md** (meta-learning)
   - Did the human explicitly say "debt" / "refactor later" / "temporary workaround"? → **tech_debt.md**
   - Does it require a specific future action with measurable scope? → **tech_debt.md**
   - Is it a lesson learned about process, not code? → **lessons.md**

   Append to `{{PROJECT_ROOT}}/.icm-main/docs/tech_debt.md` respecting strict frontmatter. If the decision tree produces "lessons.md", do NOT also write to tech_debt.md (no duplication). If no feedback explicitly cites debt OR matches tech_debt criteria, skip this step (lessons-only).
4. Atomic commit (pre-commit validates L1↔outputs↔lessons atomicity; commit-msg prefix `intake:` or `feedback:`). Tech debt append (if any) must commit via `cd .icm-main && git commit ...` (ADR-style workflow — see L0 R6):
   ```
   intake: workspace <NNN> close (output A) + lessons + tech_debt append
   ```
5. **CLAUDE.md root + last-active detection:** run `python {{SKILL_DIR}}/scripts/handoff.py remove-block --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --skill-dir {{SKILL_DIR}} --closed-at <ISO> --outcome A --exit-2-if-last-active`. Capture exit code:
   - `0` = other active workspaces remain (ICM region remains populated).
   - `2` = was the last active (ICM region replaced with idle msg + persisted in base via `.icm-main/`).
6. **(v3.7.0) Auto-invoke `/init` if was último ativo (last active):** if exit code from step 5 = `2`, invoke `Skill(skill: "init")` in the SAME session before step 7 (cleanup). Justification: after output A of the last workspace, ICM region is idle and the codebase region needs to be regenerated with info about built code (last merge stage 07). If exit = `0`, **DO NOT invoke** `/init` — other workspaces still active, ICM region populated, `/init` would overwrite signaling (forbidden — see `_references/runtime/project-root-claude-md.md` §"Contract with /init"). Skip to step 8 in that case (no cleanup).
7. **(v3.7.2) Opt-in cleanup menu (only if exit=2):** AFTER `/init`, offer complete ICM-ephemeral state cleanup (delete workspace branch, remove `.icm-main/` worktree, clean orphan subagent worktrees). Print literal:

   ```
   🧹 Full ICM cleanup? Will execute:
     - git checkout main at root (project_root reverts to reflect product code)
     - git worktree remove .icm-main (redundant parallel worktree)
     - git branch -D workspace/<NNN-slug> (closed workspace branch)
     - git worktree prune (orphan subagent worktrees from stage 04)

   [s] yes, execute cleanup
   [n] no, keep current state (manual cleanup later via scripts/icm-cleanup.py)
   [dry-run] show what would run without executing
   ```

   - If human replies `[dry-run]`: invoke `Bash(python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --dry-run)`. Show output. Re-ask menu.
   - If human replies `[s]`: invoke `Bash(python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}})`. Print output.
   - If human replies `[n]`: skip cleanup, print `ICM state kept. For manual cleanup later: python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}}`.

   Cleanup is **opt-in with confirmation** because it is destructive (deletes branch + worktrees). Pre-checks in the script automatically abort if there are uncommitted changes — human can investigate first.

   Canonical doc: `_references/runtime/icm-cleanup-protocol.md`.

8. Print for user — varies per exit code from step 5:
   - exit `2`: `✅ Workspace <NNN-slug> CLOSED (output A). Lessons recorded in docs/lessons.md. Was last active (último ativo) → /init triggered to regenerate CLAUDE.md root + ICM cleanup <executed/skipped/dry-run per choice>.` (+ "Tech debt recorded in docs/tech_debt.md." if step 3 executed).
   - exit `0`: `✅ Workspace <NNN-slug> CLOSED (output A). Lessons recorded in docs/lessons.md. <K> workspace(s) still active — /init and cleanup NOT triggered.`
9. **Do NOT generate `_kickoff.md`.** EXIT the session.

### Exit B — Restart stage X

1. Validate `X ∈ {01, 02, 03, 04, 05, 06, 07}` (refuse `00` and `08`).
2. Move old outputs: `stages/<XX>/output/` → `stages/<XX>/output-iteration-<N>/` (N = iteration BEFORE increment).
3. **Update L1**:
   - `iteration = N+1`
   - `stage_atual = <XX>`
   - `sub_stage = <XX>_in_progress` (or `04_wave_1_in_progress` if X=04)
   - `status = IN_PROGRESS`
   - `last_transition.from = 08_in_progress`
   - `last_transition.to = <XX>_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "iteration_increment", from: "08_in_progress", to: "<XX>_in_progress", commit_sha, note: "output B restart stage X"}`
4. **Render `_kickoff.md`** in `<workspace>/stages/<XX>_<name>/_kickoff.md`:
   - `prev_outputs` inherits from `intake-report.md` (summary of lessons + 4 feedback blocks)
   - `pending_for_this_stage`: points from feedback that motivated the restart
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render`
   - **Script CLI reference:** `references/script-cli-reference.md` — exact format for `--prev-outputs`, `--pending`, and all other flags.
5. Atomic commit (prefix `intake:` or `feedback:`):
   ```
   intake: workspace <NNN> restart stage <XX> (output B, iteration <N+1>) + kickoff
   ```
   Files in commit: `intake-report.md` + L1 + outputs moved to `output-iteration-<N>/` + `_kickoff.md` of stage X.
6. **Print verbal KICKOFF block** for user (copy-paste):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   🔁 Stage 08 OUTPUT B — restart stage <XX> — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=<XX>, sub_stage=<XX>_in_progress, iteration=<N+1>
     - Old outputs moved: stages/<XX>/output-iteration-<N>/
     - Kickoff: stages/<XX>_<name>/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage <XX> (<name>) — iteration <N+1>.

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/<XX>_<name>/CONTEXT.md
     workspaces/<NNN-slug>/stages/<XX>_<name>/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```
7. EXIT the session.

### Exit C — Spawn new workspace

1. **Update L1**:
   - `sub_stage = 08_decided_C`
   - `status = COMPLETED`
   - `spawn_to = <new-workspace-slug>`
   - `last_transition.from = 08_in_progress`
   - `last_transition.to = 08_decided_C`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from, to, commit_sha, note: "output C spawn"}`
2. Atomic commit:
   ```
   intake: workspace <NNN> close + spawn <new-slug> (output C)
   ```
3. **(v3.7.0) Render `.icm/spawn-pending.json`** in `{{PROJECT_ROOT}}/.icm/spawn-pending.json` (gitignored). Schema:
   ```json
   {
     "spawn_from": "{{WORKSPACE}}",
     "intake_report_path": "workspaces/{{WORKSPACE}}/stages/08_feedback_intake/output/intake-report.md",
     "intake_report_branch": "workspace/{{WORKSPACE}}",
     "proposed_workspace_name": "<new-workspace-slug>",
     "proposed_profile": "<suggested profile based on scope>",
     "proposed_tier": "<suggested tier>",
     "intake_commit_sha": "<sha from step 2 commit>",
     "agent_brief": {
       "por_que_spawn": "...",
       "escopo_motivador": "...",
       "heranca_aplicavel": "...",
       "nao_quero": "...",
       "notes_livre": ""
     },
     "created_at": "<ISO 8601>"
   }
   ```
   `agent_brief` consumable by the new workspace's recon-report (stage 00 reads + cites inheritance). Next session bootstrap auto-detects the file (`bootstrap.detect_spawn_pending`), proposes values, unlinks post-success.
4. **Do NOT generate `_kickoff.md`** (new workspace is another; bootstrap happens in separate session).
5. **CLAUDE.md root + last-active detection:** `python {{SKILL_DIR}}/scripts/handoff.py remove-block --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --skill-dir {{SKILL_DIR}} --closed-at <ISO> --outcome C --spawn-to <new-slug> --exit-2-if-last-active`. Capture exit code:
   - `0` = other active workspaces remain.
   - `2` = was the last active (ICM region replaced with idle msg).
6. **(v3.7.0) Auto-invoke `/init` if was último ativo (last active):** if exit code from step 5 = `2`, invoke `Skill(skill: "init")` in the SAME session BEFORE step 7 (cleanup). Justification: after output C of the last workspace, ICM region is idle and the codebase region needs to be regenerated to reflect code built before the pivot (human will still bootstrap new workspace in a separate session — `/init` captures current code snapshot). If exit = `0`, **DO NOT invoke** `/init`. Skip to step 8 in that case (no cleanup).
7. **(v3.7.2) Opt-in cleanup menu (only if exit=2):** AFTER `/init`, offer complete ICM-ephemeral state cleanup (delete workspace branch, remove `.icm-main/` worktree, clean orphan subagent worktrees). Print literal:

   ```
   🧹 Full ICM cleanup? Will execute:
     - git checkout main at root (project_root reverts to reflect product code)
     - git worktree remove .icm-main (redundant parallel worktree)
     - git branch -D workspace/<NNN-slug> (closed workspace branch)
     - git worktree prune (orphan subagent worktrees from stage 04)

   ⚠️  Output C: new workspace will be bootstrapped in a separate session via
   /xp-icm-workflow. Bootstrap recreates .icm-main/ if absent. Cleaning now
   is safe — bootstrap rebuilds whatever it needs.

   [s] yes, execute cleanup
   [n] no, keep current state (manual cleanup later via scripts/icm-cleanup.py)
   [dry-run] show what would run without executing
   ```

   - If human replies `[dry-run]`: invoke `Bash(python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --dry-run)`. Show output. Re-ask menu.
   - If human replies `[s]`: invoke `Bash(python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}})`. Print output.
   - If human replies `[n]`: skip cleanup, print `ICM state kept. For manual cleanup later: python {{SKILL_DIR}}/scripts/icm-cleanup.py --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}}`.

   Canonical doc: `_references/runtime/icm-cleanup-protocol.md`.

8. Print for user — explicit instruction for next session:

   - If exit `2` (last active, /init triggered):
     ```
     ✅ Workspace <NNN-slug> CLOSED + SPAWN registered (output C). Was last active → /init triggered to regenerate CLAUDE.md root.

     Next step (human, new session):

       /xp-icm-workflow project-root={{PROJECT_ROOT}}

     Bootstrap auto-detects .icm/spawn-pending.json and proposes:
       - profile=<suggested profile>
       - tier=<suggested tier>
       - workspace-name=<new-slug>
       - spawn_from={{WORKSPACE}}

     You confirm or adjust in the interactive menu.
     (Explicit fallback: --spawn-from={{WORKSPACE}} arg over file.)
     ```

   - If exit `0` (other active workspaces remain):
     ```
     ✅ Workspace <NNN-slug> CLOSED + SPAWN registered (output C). <K> workspace(s) still active — /init NOT triggered.

     Next step (human, new session):

       /xp-icm-workflow project-root={{PROJECT_ROOT}}

     Bootstrap auto-detects .icm/spawn-pending.json and proposes:
       - profile=<suggested profile>
       - tier=<suggested tier>
       - workspace-name=<new-slug>
       - spawn_from={{WORKSPACE}}

     You confirm or adjust in the interactive menu.
     (Explicit fallback: --spawn-from={{WORKSPACE}} arg over file.)
     ```
9. EXIT the session.

Details in `<skill_root>/references/session-handoff-protocol.md`.

---

## v3.3.0 references applicable to this stage

- **Triage state machine (`_references/runtime/triage-state-machine.md`):**
  BEFORE A/B/C inference, classify feedback in (category, state):
  - bug → Output B (restart stage X)
  - accepted enhancement → Output C (spawn new workspace)
  - rejected enhancement → wontfix → append to `_out-of-scope/` + Output A
  - all OK → Output A
  Each B/C item produces AGENT-BRIEF (format:
  `_references/runtime/agent-brief-template.md`).

- **OUT-OF-SCOPE wontfix (`_references/runtime/out-of-scope-kb.md`):**
  rejected enhancement → create/update `<workspace>/_out-of-scope/<concept-kebab>.md`
  with decision + durable reason + prior requests.

- **CLAUDE.md root update:**
  - **Output A:** `python {{SKILL_DIR}}/scripts/handoff.py remove-block --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --skill-dir {{SKILL_DIR}} --closed-at <ISO8601> --exit-2-if-last-active`. If it was the last active, automatically activates idle region + **(v3.7.0)** session auto-invokes `Skill(skill: "init")` to regenerate CLAUDE.md root codebase region.
  - **Output B:** `python {{SKILL_DIR}}/scripts/handoff.py update-project-md --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} --profile {{PROFILE}} --tier {{TIER}} --stage-atual <X> --stage-dir <X_name> --sub-stage <X>_in_progress --iteration <N+1> --status IN_PROGRESS --skill-dir {{SKILL_DIR}}`. **(v3.7.0)** `/init` is NOT triggered — workspace remains active.
  - **Output C:** `remove-block ... --outcome C --spawn-to <new-slug> --exit-2-if-last-active` (owning workspace becomes COMPLETED). If it was the last active, **(v3.7.0)** session auto-invokes `/init` same as output A. Bootstrap in session B adds block of new workspace.
