---
layer: L2
stage: "00"
stage_name: "recon"
sub_stage_enum:
  - "00_in_progress"
  - "00_completed"
applicable_stop_points:
  - "workspace_corrupt"
  - "profile_mismatch"
output_files:
  - "output/recon-report.md"
next_stage: "01"
---

# Stage 00 — recon (L2)

Initial reconnaissance of the project. Detects workspace type (greenfield, existing, external_repo), validates coherence between declared profile/tier and the actual repository state, lists active ADRs and inheritable lessons. Output feeds discovery (stage 01) with a factual baseline — no invented context that is not in the FS.

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/.icm-profile.local.yaml | L3 | conditional: exists if human declared local override |
| 5 | {{PROJECT_ROOT}}/.git/config | L3 | yes (read-only — checks base_branch + remotes) |
| 6 | {{PROJECT_ROOT}}/.icm-main/docs/lessons.md | L3 | conditional: exists if workspace was spawned from stage 08 output C or inherits from a prior iteration |
| 7 | {{PROJECT_ROOT}}/.icm-main/docs/decisions/ | L3 | conditional: lists index of existing ADRs (without reading each body) |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/profile-effective.yaml | L3 | yes |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/brainstorming-200tok.md | L3 | yes |
| 10 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/writing-plans-200tok.md | L3 | yes |
| 11 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. In stage 00 only exists if the workspace was spawned from stage 08 output C (inherited workspace). |
| 12 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/_seed.md | L4-seed | conditional: generated by the skill bootstrap. Present when user invoked `/xp-icm-workflow` with a free-form description (inferred intent). Contains original intent, inferred profile/tier, and pending items. |
| 13 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 14 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |
| 15 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/state-machine-schema.md | L3 | conditional: referenced in pre-flight §R2.7 |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/ and {{PROJECT_ROOT}}/.icm-main/tests/ — stage 00 does NOT inspect source code; only repository metadata.
- Individual content of ADRs in {{PROJECT_ROOT}}/.icm-main/docs/decisions/*.md — only the index (filenames). Detailed reading happens in stage 02.
- Outputs of stages 01+ — they do not exist yet.
- Sibling workspaces in {{PROJECT_ROOT}}/workspaces/<other>/ — this workspace's scope is {{WORKSPACE}}.

## Process

1. **Pre-flight:** validate that all Input paths marked `yes` exist; sub_stage `00_in_progress`. If a required path is absent → `status: BLOCKED`, `block_reason: error`. Also validate:
   - **CWD and branch:** `cd {{PROJECT_ROOT}}` (all relative paths in this stage resolve from here). `git branch --show-current` MUST show `workspace/{{WORKSPACE}}`. Wrong branch → `status: BLOCKED, block_reason: error`.
   - `{{PROJECT_ROOT}}/.icm-main/` worktree exists and is checked out to `{{BASE_BRANCH}}` (model v3.4.0). Absent → `status: BLOCKED, block_reason: error` with suggestion `git worktree add .icm-main {{BASE_BRANCH}}`.
   - `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/.claude/hooks/context-check.sh` exists and is executable, and `{{PROJECT_ROOT}}/.claude/settings.local.json` contains a `hooks.PostToolUse` entry pointing to `bash workspaces/{{WORKSPACE}}/.claude/hooks/context-check.sh`. If absent → warning (does not block bootstrap, but the anti-compact context checkpoint runs without automatic enforcement).
2. **Detect workspace type:** classify as `greenfield` (no populated `src/`, no ADRs), `existing` (repository with code + prior ADRs), or `external_repo` (read-only clone that will produce a reading/analysis workspace). Decision based on listing `{{PROJECT_ROOT}}/.icm-main/src/` (existence only), `{{PROJECT_ROOT}}/.icm-main/docs/decisions/` (file count), and `git remote -v`.
3. **Validate profile×tier coherence vs actual state:** compare `profile_base` and `tier` from L0/L1 against the FS reality. Mismatch signals — e.g., tier `experimental` in a repo with a release tag; profile `cli_tool` in a repo with a web app — trigger stop point `profile_mismatch`.
4. **Validate workspace integrity:** run heuristics from `{{SKILL_DIR}}/references/state-machine-schema.md` §R2.7 (hash mismatch, inconsistent history, missing commit_sha). Any failure → stop point `workspace_corrupt` proposing Recovery Wizard.
5. **List active ADRs:** glob `{{PROJECT_ROOT}}/.icm-main/docs/decisions/*.md` → record filename + title (first line) without reading body. List will feed stage 02.
6. **Record inheritance (if `spawn_from`):** if L1 declares `spawn_from: <workspace>`, read `{{PROJECT_ROOT}}/.icm-main/docs/lessons.md` and cite applicable inheritable lessons in `recon-report.md`. If absent, note "no inheritance".
7. **Consult superpowers summaries** (brainstorming + writing-plans 200tok) to frame the report style — direct, factual, no invention.
8. **Write `output/recon-report.md`** (relative to workspace root `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/00_recon/`) with fixed sections: Workspace type; Profile×tier check; Active ADRs (index); Inheritable lessons; Pre-triggered stop points (if any); Suggested next steps for 01_discovery.
9. **Update L1** (`{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md`): `stage_atual = 01`, `sub_stage = 01_in_progress`, `status = BLOCKED`, `block_reason = human_gate`, set `prev_outputs` (recon report path), set `pending` (next: discovery stage), append `history` event `stage_transition`. Atomic commit (pre-commit hook validates L1↔outputs atomicity). Human approval happens inline — reply "proceed" sets `status = IN_PROGRESS`, removes `block_reason`.

## Outputs

- `output/recon-report.md` — reconnaissance report: workspace type, profile/tier validation, ADR index, inheritable lessons, pre-triggered stops, next steps for 01.

## Sub_stage transitions

Valid enum: `00_in_progress`, `00_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/recon-report.md` exists in the FS.
- Profile×tier validation ran (result documented in report).
- Integrity heuristics ran (result documented in report).
- Human approved via gate (status `BLOCKED`, `block_reason = human_gate` → human replies "proceed" → set `status = IN_PROGRESS`, remove `block_reason`).

## Canonical statuses available in this stage

- `IN_PROGRESS` — recon active, reading repository metadata.
- `BLOCKED` — requires `block_reason`. Values: `human_gate` (recon report ready, awaiting human approval), `stop_point` (workspace_corrupt or profile_mismatch A/B/C menu), `error` (required Input path absent, hook rejected commit, invalid git config).

## Applicable stop points

Canonical catalogue in `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md`. IDs triggerable in stage 00 recon:

- `workspace_corrupt` — inconsistency between L1 frontmatter and actual FS state (hash mismatch, outputs absent in history, missing commit_sha). Always `hard`. Menu proposes Recovery Wizard as option A.
- `profile_mismatch` — profile/tier declared in L0/L1 do not match the actual project scope detected by recon. Always `hard`. Menu proposes: A) adjust profile/tier, B) spawn new workspace, C) reduce scope.

Trigger: agent pauses, writes A/B/C menu to `output/recon-report.md § Stop points`, updates L1 `status: BLOCKED`, `block_reason = stop_point`. Human responds, session resumes with `IN_PROGRESS`.

## Skill superpowers reference

200tok summaries (mandatory consultation; formal skill only if complexity justifies):

- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/brainstorming-200tok.md`
- `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/writing-plans-200tok.md`

Formal skills (escape hatch): `superpowers:brainstorming`, `superpowers:writing-plans`.

## Gates

- **Human:** reviews `output/recon-report.md`. Confirms "is this recon-report correct? proceed to 01?" before transitioning.
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`.
- **Approval to transition:** human explicitly approves; sub_stage becomes `00_completed` in the commit that records the approval.

## End of stage handoff (1-stage-1-session)

Upon completing this stage, session must:

1. **Update L1** (`{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md`):
   - `stage_atual = 01`
   - `sub_stage = 01_in_progress`
   - `status = BLOCKED`, `block_reason = human_gate`
   - Set `prev_outputs`: `[stages/00_recon/output/recon-report.md]`
   - Set `pending`: `[next: discovery stage 01]`
   - `last_transition.from = 00_in_progress`
   - `last_transition.to = 01_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "00_in_progress", to: "01_in_progress", commit_sha, note: "recon complete, awaiting human gate"}`

2. **Render `_kickoff.md`** in the next stage:
   - Path: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/01_discovery/_kickoff.md`
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render` or function `render_kickoff` from `{{SKILL_DIR}}/scripts/handoff.py`
   - **Script CLI reference:** `references/script-cli-reference.md` — exact format for `--prev-outputs`, `--pending`, and all other flags.
   - L4-kickoff YAML frontmatter per schema in `references/session-handoff-protocol.md`
   - Body: prev_outputs with summary + prev_decisions + pending for next stage

3. **Atomic commit** (pre-commit hook validates outputs↔L1; commit-msg validates prefix):
   ```
   workspace <NNN>: stage 00 complete + kickoff stage 01
   ```
   Files in commit: current stage outputs + L1 + `_kickoff.md` of the next stage.

3b. **Update project root CLAUDE.md dashboard:**
   ```bash
   python {{SKILL_DIR}}/scripts/handoff.py update-project-md \
       --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} \
       --profile {{PROFILE}} --tier {{TIER}} \
       --stage-atual 01 --stage-dir 01_discovery \
       --sub-stage 01_in_progress --status IN_PROGRESS \
       --skill-dir {{SKILL_DIR}}
   ```

4. **Print verbal KICKOFF block** for user (copy-paste). Template (replace placeholders):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 00 (recon) COMPLETE — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=01, sub_stage=01_in_progress
     - Outputs: <list>
     - Kickoff: stages/01_discovery/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 01 (discovery).

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/01_discovery/CONTEXT.md
     workspaces/<NNN-slug>/stages/01_discovery/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

5. **EXIT** the session. Do NOT continue to the next stage in the same session.

Details in `{{SKILL_DIR}}/references/session-handoff-protocol.md`.

---

## v3.3.0 references applicable to this stage

- **Module map skeleton (zoom-out pattern):** when encountering an unknown module
  during recon, zoom out and map callers. Note candidate terms
  for the glossary (next session of stage 01 will resolve them in
  `_config/CONTEXT.md`).
- **Output:** `_config/CONTEXT.md` is created empty by bootstrap; stage 01
  will populate it.

### Zoom-out workflow (v3.4.1) — when encountering an unknown module

You are doing project recon and you stumbled upon a file/module whose
purpose is not clear from its direct content. Do NOT dive into it line by line.
Zoom out:

1. **Map callers** — run `Grep` or Bash:
   ```
   Grep -r "from <module>" {{PROJECT_ROOT}}/.icm-main/src/
   Grep -r "import <module>" {{PROJECT_ROOT}}/.icm-main/src/
   ```
   List 3-5 main callers. Do not cite all — only the representative ones.

2. **Identify 1 caller that looks like the "root"** — usually the one
   at the top of the call graph (least called by others). Read that caller first.

3. **Note new terms in recon-report** — any technical names
   (classes, functions, domain concepts) that appeared during this
   zoom-out should become ubiquitous language candidates. Add section
   `### Glossary candidates` to `output/recon-report.md`. Stage 01 will
   resolve these into official entries in `_config/CONTEXT.md`.

4. **Do not document the module now** — recon is not design. Only record:
   "Module X is touched by callers A, B, C. Deepen in stage 01 (discovery)
   if relevant to the workspace objective." Skipping details avoids
   spending context on irrelevant code.

5. **Explicit limit** — if zoom-out requires more than 3 levels of
   indirection (caller → caller → caller), stop. Note in recon-report:
   "Depth > 3 — investigation deferred to stage 01 on demand".

Anti-pattern: reading an unknown file line by line without context. Costs
context without proportional gain. Recon is a map, not exploration.
