---
layer: L2
stage: "03"
stage_name: "wave_planner"
sub_stage_enum:
  - "03_in_progress"
  - "03_completed"
applicable_stop_points: []
output_files:
  - "output/wave-plan.md"
next_stage: "04"
---

# Stage 03 — wave_planner (L2)

Runs the deterministic wave-planner on top of the `plan.md` from stage 02 design. Builds a DAG from explicit dependencies and file footprints, partitions tasks into topological waves respecting the subagent cap per tier (2/3/5/5), and writes `wave-plan.md` with the list of branches to create for stage 04. This stage is deterministic: cycles in the plan become `BLOCKED_ERROR`, not a stop point.

## Inputs (reads ONLY these, in order)

| # | Path | Layer | Required? |
|---|------|-------|-----------|
| 1 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CLAUDE.md | L0 | yes |
| 2 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md | L1 | yes |
| 3 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/CONTEXT.md | L2 | yes |
| 4 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md | L4 | yes |
| 5 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_config/profile-effective.yaml | L3 | yes |
| 6 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/dispatching-parallel-agents-200tok.md | L3 | yes |
| 7 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/_kickoff.md | L4-kickoff | conditional: generated by the previous session. Absent in beta1/beta2 workspaces (4B legacy) or if this is the first session of the stage. |
| 8 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/session-handoff-protocol.md | L3 | conditional: required for the stage's final handoff |
| 9 | {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/runtime/stop-points-canonical.md | L3 | conditional: canonical catalogue of IDs, complementary to _config/stop-points.md for thresholds |

## Does Not Read (negative constraint)

- {{PROJECT_ROOT}}/.icm-main/src/, {{PROJECT_ROOT}}/.icm-main/tests/
- {{PROJECT_ROOT}}/.icm-main/docs/decisions/ (ADRs already read by stage 02; wave-planner only reads metadata in plan.md)
- Outputs of other stages besides `02_design/output/plan.md`
- {{PROJECT_ROOT}}/.icm-main/docs/lessons.md (lessons will be injected by lead in stage 04)

## Process

1. Pre-flight: validate Input paths exist; sub_stage `03_in_progress`.
2. Read `profile-effective.yaml` to extract effective `tier` and `profile` (cap = `min(tier_cap, profile_override)`).
3. Run the deterministic wave-planner (canonical CLI, absolute paths resolved):
   ```
   python {{SKILL_DIR}}/scripts/wave-planner-script.py \
     --plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md \
     --tier <tier> \
     --profile <profile> \
     --workspace {{WORKSPACE}} \
     --output {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/wave-plan.md
   ```
4. If the script exits with exit ≠ 0 (cycle, duplicate slug, unknown dependency, invalid schema) → set `status: BLOCKED_ERROR`, record error in `history`, and stop. Do NOT trigger a stop point — `applicable_stop_points: []`.
5. Script stdout reports `total_tasks`, `total_waves`, `total_sub_waves`, `ambiguities`. Append as note in `last_action`.
6. Run LLM review (`python {{SKILL_DIR}}/scripts/wave-planner-llm-review.py`). Canonical CLI:
   ```
   python {{SKILL_DIR}}/scripts/wave-planner-llm-review.py \
     --wave-plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/wave-plan.md \
     --plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/02_design/output/plan.md \
     --ambiguities {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/ambiguities-resolved.md \
     --output {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/llm-review-verdict.json \
     --update-wave-plan {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/stages/03_wave_planner/output/wave-plan.md \
     --workspace-context {{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/CONTEXT.md
   ```
   If skip threshold is met (≤2 tasks or ≤1 wave) → exits with `SKIPPED` in frontmatter. If `--llm-response` is provided → validates and applies. If no response provided → script prints formatted prompt (exit 2); human/external algorithm runs LLM and passes JSON back via `--llm-response`. `--update-wave-plan` updates the `wave-plan.md` frontmatter with `llm_review: APPROVE|PROPOSE_CHANGES|SKIPPED` and increments `llm_review_iterations`.
7. **End-of-stage handoff:** follow the gate-inline protocol in the `## End of stage handoff` section of this L2 (Phase 1 WORK_DONE → human gate → Phase 2 GATE_APPROVED).

## Outputs

- `output/wave-plan.md` — frontmatter (cap, total_tasks, total_waves, llm_review status) + table per sub-wave (slug, files touched, depends on, branch to create) + audit (serialized file conflicts, ambiguities).

## Sub_stage transitions

Valid enum: `03_in_progress`, `03_completed`.

IN_PROGRESS → COMPLETED transition fires when:
- `output/wave-plan.md` exists.
- Wave-planner exited with exit 0 (no cycle, no invalid schema).
- Human approved via gate (status `COMPLETED_AWAITING_HUMAN` → human responds).

## Canonical statuses available in this stage

- `IN_PROGRESS` — running wave-planner.
- `COMPLETED_AWAITING_HUMAN` — `wave-plan.md` ready, human reviews cap/ambiguities.
- `BLOCKED_ERROR` — wave-planner failed (cycle, duplicate slug, unknown dependency, invalid schema in plan.md).

## Applicable stop points

Canonical catalogue in `references/stop-points-canonical.md`. **No stop points applicable in this stage** — wave-planner is deterministic. Failures (cycle, unresolvable ambiguity) become `BLOCKED_ERROR`, human fixes `plan.md` and re-runs.

## Skill superpowers reference

200tok summary: `{{PROJECT_ROOT}}/workspaces/{{WORKSPACE}}/_references/superpowers-summary/dispatching-parallel-agents-200tok.md`

Formal skill: `superpowers:dispatching-parallel-agents` (escape hatch — only if human requests a detailed explanation of parallelism).

## Gates

- **Human:** reviews `output/wave-plan.md`, validates applied cap, examines ambiguities, approves or requests adjustment in `plan.md` (returns to stage 02).
- **Automatic (CI):** pre-commit hook validates L1↔outputs atomicity and commit prefix `workspace/{{WORKSPACE}}`.
- **Approval to transition:** human explicitly approves; sub_stage becomes `03_completed` in the next commit.

## End of stage handoff (gate inline + 1-stage-1-session)

Handoff is split into TWO phases within the SAME session. Human gate sits between them — `_kickoff.md` is only rendered AFTER approval. Bug v3.4.2 fixed: premature render+exit before approval created loop "kickoff → user approves in new session → kickoff again". Canonical doc: `<skill_root>/references/session-handoff-protocol.md`.

### Phase 1: WORK_DONE (after outputs are ready)

1. **Update L1** (`<workspace>/CONTEXT.md`):
   - `sub_stage = 03_completed`
   - `status = COMPLETED_AWAITING_HUMAN`
   - `last_transition.from = 03_in_progress`
   - `last_transition.to = 03_completed`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "03_in_progress", to: "03_completed", commit_sha, note: "work done, awaiting gate"}`

2. **Atomic commit 1/2** (outputs + L1; pre-commit hook validates atomicity):
   ```
   workspace <NNN>: stage 03 work done, awaiting gate
   ```
   Files: current stage outputs + L1. **DO NOT** include `_kickoff.md` (not rendered yet).

3. **Print gate prompt** for human. Do NOT exit the session. Do NOT render `_kickoff.md`:

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 03 (wave_planner) work COMPLETE — workspace <NNN-slug>

   Outputs ready for review:
     - <list of paths>

   L1: sub_stage=03_completed, status=COMPLETED_AWAITING_HUMAN
   Commit 1/2: <sha>

   🛑 Human gate: review wave-plan.md (applied cap, resolved ambiguities).
   Reply in chat:
     - "approved" / "ok proceed to 04" → I render kickoff and exit
     - "adjust X" → I return to work with your request (status=IN_PROGRESS)
     - "abort" → I mark workspace BLOCKED_ERROR
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ```

4. **WAIT for human response** in the SAME session.

### Phase 2: GATE_APPROVED (after human replies "approved")

5. **Update L1** (second transition — entry into stage 04 starts from wave 1):
   - `stage_atual = 04`
   - `sub_stage = 04_wave_1_in_progress`
   - `status = IN_PROGRESS`
   - `last_transition.from = 03_completed`
   - `last_transition.to = 04_wave_1_in_progress`
   - `last_transition.at = <ISO 8601 UTC now>`
   - `history` append: `{at, event: "stage_transition", from: "03_completed", to: "04_wave_1_in_progress", commit_sha, note: "gate approved by human"}`

6. **Render `_kickoff.md`** in the next stage:
   - Path: `<workspace>/stages/04_implementation_waves/_kickoff.md`
   - Use `python {{SKILL_DIR}}/scripts/handoff.py render` or function `render_kickoff` from `{{SKILL_DIR}}/scripts/handoff.py`
   - **Script CLI reference:** `references/script-cli-reference.md` — exact format for `--prev-outputs`, `--pending`, and all other flags.
   - L4-kickoff YAML frontmatter per schema in `references/session-handoff-protocol.md`
   - Body: prev_outputs + prev_decisions + pending for next stage (including wave 1 to execute)

7. **Atomic commit 2/2** (kickoff + L1):
   ```
   workspace <NNN>: gate approved, kickoff stage 04
   ```
   Files: next stage `_kickoff.md` + updated L1.

8. **Update project root CLAUDE.md dashboard:**
   ```bash
   python {{SKILL_DIR}}/scripts/handoff.py update-project-md \
       --project-root {{PROJECT_ROOT}} --workspace {{WORKSPACE}} \
       --profile {{PROFILE}} --tier {{TIER}} \
       --stage-atual 04 --stage-dir 04_implementation_waves \
       --sub-stage 04_wave_1_in_progress --status IN_PROGRESS \
       --skill-dir {{SKILL_DIR}}
   ```

9. **Print verbal KICKOFF block** for user (copy-paste for next session):

   ```
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   ✅ Stage 03 (wave_planner) GATE APPROVED — workspace <NNN-slug>

   Workspace updated at commit <sha>:
     - L1: stage_atual=04, sub_stage=04_wave_1_in_progress, status=IN_PROGRESS
     - Kickoff: stages/04_implementation_waves/_kickoff.md generated

   🔄 KICKOFF next session — copy/paste:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   Continue workspace <NNN-slug> at stage 04 (implementation_waves) — wave 1.

   Read order:
     workspaces/<NNN-slug>/CLAUDE.md
     workspaces/<NNN-slug>/CONTEXT.md
     workspaces/<NNN-slug>/stages/04_implementation_waves/CONTEXT.md
     workspaces/<NNN-slug>/stages/04_implementation_waves/_kickoff.md
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Close this session (Ctrl+D or /exit) and open a new Claude session
   at the project_root, then paste the prompt above.
   ```

10. **EXIT** the session. Do NOT continue to the next stage in the same session.

### Response "adjust X" (gate rejected)

If human replies with free text requesting an adjustment:
- Update L1: `status = IN_PROGRESS`, append history `{event: "gate_rejected", note: "human requested adjustment: X"}`. Sub_stage stays `03_completed` (returns to `03_in_progress` if change is non-trivial).
- Return to work as requested.
- When outputs are redone, return to Phase 1 (new commit 1/2 + new gate prompt).

### Response "abort"

If human replies "abort":
- Update L1: `status = BLOCKED_ERROR`, append history `{event: "blocked_error", error_type: "human_abort", note: "human aborted at gate"}`.
- Commit + exit. Workspace stays in BLOCKED_ERROR awaiting manual intervention.

---

## v3.3.0 references applicable to this stage

- **HITL/AFK respect (`_references/runtime/task-types-hitl-afk.md`):**
  wave-planner respects the `Type` field per task. `HITL` tasks stay in
  **isolated wave with cap=1** (sub_stage `wave-N_hitl_pending`). `AFK`
  tasks grouped normally respecting cap per tier.
- **Output `wave-plan.md`:** add `Type` column in the per-sub-wave table.
